### ISSUE TITLE
Changelog should be updated with NPM repository version

### ISSUE THREAD

**Issue by luislobo** [html-to-text/node-html-to-text#101]

**Comment by fiznool** [comment]
I see that npm is on v3.0.0. Was there a breaking change in this release?

**Comment by mlegenhausen** [comment]
The API has not changed, your application should run as before. But please check your output, there may be minor changes due to the exchange of the `htmlparser` dependency introduced in v3.0.0.

**Comment by KillyMXI** [comment]
I think this can be closed safely.
