### ISSUE TITLE
Whitespace before links is eaten rather than collapsed

### ISSUE THREAD

**Issue by curiousdannii** [html-to-text/node-html-to-text#107]
```
htmlToText.fromString('aaa   \n\t\t<a>bbb</a>')
htmlToText.fromString('aaa   \n<a>bbb</a>')
htmlToText.fromString('aaa   \n \n<a>bbb</a>')
```

These all return `aaabbb` but they should return `aaa bbb`

Curiously

```
 htmlToText.fromString('aaa   \n\t\t <a>bbb</a>')
```

works correctly, but if the character immediately prior to the `<` is anything other than a space, all the whitespace is eaten.

**Comment by mlegenhausen** [comment]
Seems like we are trimming to much. Currently there is only a very simple space handling implemented, which is simply left trim everything. I am open for improvements and of cause pull requests ;)

**Comment by curiousdannii** [comment]
I don't know the internals of the package, so I'm hoping those who have been messing with the whitespace recently can take a look at fixing this...

Why is trimming necessary? Could instead you convert all whitespace into spaces, and then collapse multiple spaces to one space as a final stage? (Ignoring tables etc.)

**Comment by ianjepperson** [comment]
I think I'm seeing this same bug with `&nbsp;`
```
> html2text.fromString('aaa &nbsp;<b>bbb</b>')
'aaabbb'
```

**Comment by mlegenhausen** [comment]
I think the space handling needs a complete overhaul. There need to be rules defined which applies to all text blocks which includes handling of html entities, whitespace characters and punctuation marks.

**Comment by dmrzn** [comment]
Hi, could anyone advise any workarounds of this issue?
> html2text.fromString('aaa &nbsp;<b>bbb</b>')
'aaabbb'

**Comment by kareljuricka** [comment]
@dmrzn  I found this solution

Replace all &nbsp; with ' ' -  `html.replace(/&nbsp;/gi, ' '); `

If you want to also has <b> whitespaced, you can use this format function for all text nodes:

```
format: {
                    text: (node, options) => {
                        // console.log('node', node);
                        return ` ${node.data} `;
                    }
                }
```

It add space to all text elements.

**Comment by KillyMXI** [comment]
Version 6 has much improved whitespace handling now.
