### ISSUE TITLE
Should be spacing after period

### ISSUE THREAD

**Issue by rightaway** [html-to-text/node-html-to-text#110]
```
<a href='/some/path'>stuff</a>.

<a href='/some/path'>stuff</a>.
```

becomes

`stuff [/some/path].stuff [/some/path].`

but it should have spacing after the first period.

And when I'm using `preserveNewlines' set to true, shouldn't it be like this?

```
stuff [/some/path].

stuff [/some/path].
```

But instead it puts it on one line and ignores preserveNewlines.

**Comment by mlegenhausen** [comment]
Try to put it in a `<p>` tag.

**Comment by KillyMXI** [comment]
Version 6 is now much better handling whitespace. Both cases work as expected.
