### ISSUE TITLE
Uppercase headings breaks URLs in "a" tags inside headings

### ISSUE THREAD

**Issue by boutell** [html-to-text/node-html-to-text#116]
In an email such as an account confirmation email it's not unusual to put the one and only link the user really needs to click inside a heading such as h3.

When you pass this through html-to-text, the URL is correctly extracted and bracketed, but it also gets uppercased, making it invalid in many cases.

**Comment by boutell** [comment]
(Thanks for this very useful module!)

**Comment by mlegenhausen** [comment]
This is the currently behaviour and I think it will not change so far in the future. Cause it is really hard to "highlight" something like a heading only be using characters.

Your alternatives would be use CSS for your HTML mail to highlight your link or to improving this module by added the possibility to add custom formatters for certain tags. I am happy about every contribution.

**Comment by KillyMXI** [comment]
Version 6 now handles this properly.
