### ISSUE TITLE
show some html elements option

### ISSUE THREAD

**Issue by leonardiwagner** [html-to-text/node-html-to-text#121]
hey, I realize the intent is to convert of this lib to very-pure text , such as to print on cli

however my team is using this to only render more friendly html email, so we still need to show some tags, such as `<b>`, `<strong>`, `<i>` ....

do you guys have any interest on a PR to add a feature to "show some html tags" ?

ex.: `{ displayTags: ['b', 'strong'] } `

**Comment by mlegenhausen** [comment]
Sounds like a good idea. When designing the API it would be nice if we could provide a function for `displayTags`. Which return `true` or `false` wether the tag should be visible or not. Using an array of strings as argument is then only an api sugar.

**Comment by KillyMXI** [comment]
This can now be achieved with a custom formatter that will add `<${tagName}>` and `</${tagName}>` to the output before and after the stringified content of a tag.

```javascript
var { htmlToText } = require('html-to-text');

var text = htmlToText('<i>Hello <span>World</span></i>', {
  formatters: {
    // Create a formatter.
    'outputHtmlTag': function (elem, walk, builder, formatOptions) {
      builder.addInline('<' + formatOptions.tagName + '>');
      walk(elem.children, builder);
      builder.addInline('</' + formatOptions.tagName + '>');
    }
  },
  tags: {
    // Assign it to tags.
    'i': {
      format: 'outputHtmlTag',
      options: { tagName: 'i' }
    },
    'strong': {
      format: 'outputHtmlTag',
      options: { tagName: 'strong' }
    }
  }
});

console.log(text); // <i>Hello World</i>
```
