### ISSUE TITLE
according to documentation - ignoreHref ignore all document links if true

### ISSUE THREAD

**Issue by kchawla19** [html-to-text/node-html-to-text#124]
Couldn't make it work to ignore links but this worked 

html-to-text --ignore-href=true

**Comment by mlegenhausen** [comment]
Could you provide some example code?

**Comment by kchawla19** [comment]
sample.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="food-menu-content">
    						<li class="">
				<a href="/menu/beverages/iced-frozen-drinks/frozen-iced-mango/" data-internal="26237"><span class="item-title">Frozen Iced Mango</span><span class="item-description">Mango, Tropical Juices and a Hint of Coconut Blended with Ice and Swirled with Raspberry P...</span></a>
			</li>
 </div>
</body>
</html>


cat sample.html|html-to-text --ignoreHref=true 

Frozen Iced MangoMango, Tropical Juices and a Hint of Coconut Blended with Ice
and Swirled with Raspberry P...
[/menu/beverages/iced-frozen-drinks/frozen-iced-mango/]

cat sample.html|html-to-text --ignore-href=true

Frozen Iced MangoMango, Tropical Juices and a Hint of Coconut Blended with Ice
and Swirled with Raspberry P...

**Comment by kchawla19** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="food-menu-content">
    						<li class="">
				<a href="/menu/beverages/iced-frozen-drinks/frozen-iced-mango/" data-internal="26237"><span class="item-title">Frozen Iced Mango</span><span class="item-description">Mango, Tropical Juices and a Hint of Coconut Blended with Ice and Swirled with Raspberry P...</span></a>
			</li>
 </div>
</body>
</html>

**Comment by benpolinsky** [comment]
Can also verify that the ignore-href option removes the anchor tag, but keeps the anchor text. Is this the desired behavior?

Ex:

`<a href="http://google.com">Just Google It</a>`

Becomes:
`Just Google It`

**Comment by mlegenhausen** [comment]
Yes cause links could also be placed in text which would create "holes" otherwise.

**Comment by KillyMXI** [comment]
Can't see why this is still open.

`ignoreHref` behaves as expected.

In addition, I can note that it is possible to override format for links in order to skip them completely. But there is no way (yet) to specify which links are good to be removed and which have to retain the text content.
