### ISSUE TITLE
Strange Rendering of Standalone Lists

### ISSUE THREAD

**Issue by scottfr** [html-to-text/node-html-to-text#130]
The following list renders strangely:

`htmlToText.fromString('<ul><li>a</li><li>b</li><li>c</li></ul>')`

Expected:
```
* a
* b
* c
```
Actual (note the extra spacing for 'b' and 'c'):
```
* a
 * b
 * c
```

**Comment by jordonbiondo** [comment]
pinging @mlegenhausen or other contributors

I have a standing fix for this issue here:

https://github.com/werk85/node-html-to-text/pull/141

**Comment by jordonbiondo** [comment]
I've notice this project appears to be mostly abandoned, would you consider adding community collaborators to the project?

**Comment by mlegenhausen** [comment]
@jordonbiondo sorry for the absence, it is hard to keep track of a project that I am not activitly using anymore. Would you consider to be a collaborator for this project?

**Comment by jordonbiondo** [comment]
My ultimate desire is that the current outstanding issue fixes be merged into the project, if the current collaborators don't have the resources to do that themselves, I would be happy to help.

**Comment by KillyMXI** [comment]
Outdated issue.
