### ISSUE TITLE
Horizontal lines vanish if wordwrap is disabled

### ISSUE THREAD

**Issue by sattes-faction** [html-to-text/node-html-to-text#137]
When I set wordwrap to false or null all `<hr>`'s disappear in the generated text version. I guess it's because the "text hr" tries to be as long as the wordwrap - which obviously is zero when set to false or null.

**Comment by KillyMXI** [comment]
Version 6 now has a configurable option for `hr` length as well as the fallback value of 40 for when neither is available.
