### ISSUE TITLE
No new line between figure and paragraph

### ISSUE THREAD

**Issue by romash1408** [html-to-text/node-html-to-text#156]
This code
```javascript
var htmlToText = require("html-to-text");

htmlToText.fromString('<figure class="image">\
<imp src="..." alt="Some image">\
<figcaption>Figure caption</figcaption>\
</figure>\
<p>Next paragraph</p>');
```
returns single line
`"Figure captionNext paragraph"`

**Comment by microspec-chris** [comment]
I know this is a late reply, but you should be able to do this by including the preserveNewlines: true option:
`htmlToText.fromString(yourHTML, { preserveNewlines: true })`
This option is set to false by default.

**Comment by KillyMXI** [comment]
Version 6 is now aware of block-level tags.
Paragraphs are separated by two line breaks by default.
