### ISSUE TITLE
script tag content gets into text 

### ISSUE THREAD

**Issue by d668** [html-to-text/node-html-to-text#157]
if i do ` var text = htmlToText.fromString(html);` for attached html file, I get the content of script tag, see attached txt file.
[DrQgN3XYuB.html.txt](https://github.com/werk85/node-html-to-text/files/2069674/DrQgN3XYuB.html.txt)
[vsdfvdfsvdfvf.txt](https://github.com/werk85/node-html-to-text/files/2069670/vsdfvdfsvdfvf.txt)

**Comment by intergleam** [comment]
[DrQgN3XYuB.html.txt](https://github.com/werk85/node-html-to-text/files/2069672/DrQgN3XYuB.html.txt)

**Comment by KillyMXI** [comment]
Not sure what it was.

Doesn't seem to be an issue anymore.
