### ISSUE TITLE
Not respecting html comments tags correctly

### ISSUE THREAD

**Issue by simllll** [html-to-text/node-html-to-text#163]
E.g. 
```
<!--<div> hallo</div> --> test
<br>cat
```

Results in:
```
hallo
--> test 
cat
```

Should be:
```
test 
cat
```

Regards
Simon

**Comment by simllll** [comment]
A working regex to remove all html comments would be:
`input.replace(/(?=<!--)([\s\S]*?)-->/g, ''); // remove html comment`

regards
Simon

**Comment by KillyMXI** [comment]
Not sure what it was.

Works correctly in the version 6.
