### ISSUE TITLE
walk function doesn't get passed in for img and text formatting

### ISSUE THREAD

**Issue by Electrk** [html-to-text/node-html-to-text#175]
https://github.com/werk85/node-html-to-text/blob/b5f26807a8f8987a8a2f4a9f349ec9d0dba4a2e3/lib/html-to-text.js#L119
https://github.com/werk85/node-html-to-text/blob/b5f26807a8f8987a8a2f4a9f349ec9d0dba4a2e3/lib/html-to-text.js#L172

**Comment by KillyMXI** [comment]
In the old design the `walk` function wasn't passed to the formatters that had no need in it (no child elements).

Not relevant anymore.
