### ISSUE TITLE
Using html-to-text with Wix Corvid

### ISSUE THREAD

**Issue by amunrarara** [html-to-text/node-html-to-text#177]
I located this module from the Wix node_modules search, and I am not sure how exactly to import this module once it's been installed on my page.

**Comment by amunrarara** [comment]
Using Wix, I installed this as a module. But I do not know which "import" statement to use to bring it into my project.

**Comment by KillyMXI** [comment]
I don't know why I kept this issue open until now.
This is not a well-formed question, I don't know what it is about.
