### ISSUE TITLE
no space between words in word

### ISSUE THREAD

**Issue by HanojHanu** [html-to-text/node-html-to-text#178]
> no space "openitokay see"

`<p></p>
<div class="pasteContent" style="display:inline;" _ngcontent-c8="">
    
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <a class="e-rte-anchor" href="http://localhost:4200/shicsha" title="http:shicsha" target="_blank"
            style=" background-color: transparent; color: blue; text-decoration: none;">http:shicsha</a><br></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        open&nbsp;<strong>﻿it&nbsp;<em>﻿okay see﻿﻿</em>﻿</strong><br></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <strong style=" font-weight: bold;">join</strong></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <strong><span class="e-editor-select-start"><span class="e-editor-select-start">join here in ﻿﻿shicsha we all
                    welcome you ...</span></span></strong></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <span class="e-editor-select-end"></span></p><br class="Apple-interchange-newline"
        style=" color: rgb(51, 51, 51); font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; font-size: 12px; font-family: Roboto, &quot;Segoe UI&quot;, GeezaPro, &quot;DejaVu Serif&quot;, sans-serif, -apple-system, BlinkMacSystemFont; background-color: rgb(255, 255, 255);">
    
</div><br>
<p></p>`

**Comment by HanojHanu** [comment]
<p></p>
<div class="pasteContent" style="display:inline;" _ngcontent-c8="">
    
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <a class="e-rte-anchor" href="http://localhost:4200/shicsha" title="http:shicsha" target="_blank"
            style=" background-color: transparent; color: blue; text-decoration: none;">http:shicsha</a><br></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        open&nbsp;<strong>﻿it&nbsp;<em>﻿okay see﻿﻿</em>﻿</strong><br></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <strong style=" font-weight: bold;">join</strong></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <strong><span class="e-editor-select-start"><span class="e-editor-select-start">join here in ﻿﻿shicsha we all
                    welcome you ...</span></span></strong></p>
    <p
        style=" margin: 0px 0px 10px; font-size: 14px; font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; color: rgba(0, 0, 0, 0.87); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(255, 255, 255);">
        <span class="e-editor-select-end"></span></p><br class="Apple-interchange-newline"
        style=" color: rgb(51, 51, 51); font-style: normal; font-weight: 400; text-align: start; text-indent: 0px; white-space: normal; font-size: 12px; font-family: Roboto, &quot;Segoe UI&quot;, GeezaPro, &quot;DejaVu Serif&quot;, sans-serif, -apple-system, BlinkMacSystemFont; background-color: rgb(255, 255, 255);">
    
</div><br>
<p></p>

**Comment by KillyMXI** [comment]
I assume this was a cat walking on a keyboard.
