### ISSUE TITLE
[Feature] Ability to mark elements to be hidden from the text version

### ISSUE THREAD

**Issue by dantman** [html-to-text/node-html-to-text#179]
Right now say I have a table layout with a text avatar:
```html
<tr>
  <td class="message-avatar html-only">
    <span class="avatar text-avatar" aria-label="Avatar for John Smith">J</span>
  </td>
  <td class="message-sender">
    <p class="semantic">
      <span class="text-only" style="display: none;">Sent by: </span>
      John Smith
    </p>
  </td>
</tr>
```

Right now this will result in the very undesirable `JSent by: John Smith` instead of the desired `Sent by: John Smith`.

It would be much preferred if there was a css class, attribute, or just a filter function applied to every element that could be used to hide an element like a text avatar that is presentational only and should not end up in the text version.

**Comment by Niek** [comment]
Related issue: https://github.com/html-to-text/node-html-to-text/issues/159

**Comment by KillyMXI** [comment]
I've pushed new code addressing this issue into a separate branch - [selectors](https://github.com/html-to-text/node-html-to-text/tree/selectors)
Tracking issue: #228 

I'd be grateful if some of you can test this version on real tasks and provide your feedback before release (in a week probably).
(You can install the package directly from GitHub branch. Instruction is in the tracking issue.)

**Comment by KillyMXI** [comment]
Version 8 is now live.
Arbitrary selectors can be ignored as follows:
```js
{
  selectors: [
    { selector: 'foo.hidden', format: 'skip' }
  ]
}
```
