### ISSUE TITLE
Table class selector in multiple class don't work

### ISSUE THREAD

**Issue by Hideman85** [html-to-text/node-html-to-text#184]
Current version: html-to-text@5.1.1

The tables class selector does not work if tables has more than one class.
Take you sample in README.md
`<table class="address">` works fine with --tables=.address
`<table class="row address">` don't work with --tables=.address

Edit: Work with --tables '.row address' but it preferable with support of multiple classes

**Comment by mlegenhausen** [comment]
PR is welcome

**Comment by Hideman85** [comment]
Yes for sure but if I need to do it for all libraries that I use I won't be able to find time for my project.
I already spend time to report the issue that is not the case of all devs.

**Comment by KillyMXI** [comment]
Supported in version 6.
