### ISSUE TITLE
html character entity reference to text

### ISSUE THREAD

**Issue by roseline124** [html-to-text/node-html-to-text#194]
### description
When I load text from DB, HTML tags are removed well.
But, 'fromString()' doesn't recognize HTML character entity (like `&lt;`, `&gt;`) as HTML tags.
 
So, how about adding feature to convert HTML character entity to text ?

**Comment by roseline124** [comment]
If it's okay, please assign this issue to me

**Comment by KillyMXI** [comment]
In case you want character entities like `&lt;` and `&gt;` to be displayed as `<` and `>` - that's how it currently works.

In case you have an HTML document with all tags escaped and still want to render it in browser as HTML - you have to unescape it beforehand to prepare for rendering.
Same applies to `html-to-text` - it is just another way to "render" HTML.
It's out of scope for `html-to-text`.
