### ISSUE TITLE
Security issue in dependencies (minimist)

### ISSUE THREAD

**Issue by KillyMXI** [html-to-text/node-html-to-text#197]
https://github.com/substack/minimist
> Previous versions had a prototype pollution bug that could cause privilege escalation in some circumstances when handling untrusted user input.
> Please use version 1.2.3 or later: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

html-to-text is currently using insecure 1.2.0

**Comment by a-kriya** [comment]
Since you'd updated minimist in 20886c6, can you please publish a release?

**Comment by KillyMXI** [comment]
@a-kriya hold on a little. I got some job to do right after I picked up this project >_<
Hopefully I will find enough time to complete the next version within a week.

Before the next version is done, you can switch to https://www.npmjs.com/package/@mxiii/html-to-text
I will deprecate it only after the next version is published.

**Comment by a-kriya** [comment]
Didn't mean to sound hasty.

The security issue was just being coming up in downstream projects, so was wondering if this would be published soon. Thanks for the update.

**Comment by JohnMcLear** [comment]
Bump :)  2 months now!

**Comment by KillyMXI** [comment]
My apologies for not being able to provide reliable time estimate.

But the bump wasn't necessary either.
From the recent commits you can see I got back to work on html-to-text recently.
Progress for version 6.0.0 can be tracked in #200.

**Comment by KillyMXI** [comment]
New version is now live in npm.
I'm also going to deprecate my fork - it served it's purpose.
