### ISSUE TITLE
Very first character of a converted file is a space character

### ISSUE THREAD

**Issue by 185driver** [html-to-text/node-html-to-text#205]
Though this seems unlikely to be a bug (and more likely to be an issue on my end), I'll create this issue in the hope of resolving what I'm seeing.

Each time I convert an html document to a text file using `html-to-text`, the very first character of the resulting text file is a space character. It happens whether I use the CLI or nodejs and happens in whichever file I convert.

To reproduce this issue, copy/create the example html found [here](https://github.com/werk85/node-html-to-text#example) and convert it using basic syntax:
```sh
cat example/test.html | html-to-text > test.txt
```
This is what I see:

![image](https://user-images.githubusercontent.com/1835454/86502470-2056da00-bd69-11ea-8b21-08ccb8f68f31.png)

Is this confirmed for you too?

**Comment by KillyMXI** [comment]
Interesting. Thank you for opening the issue. (I suspect most people might just trim the output from html-to-text.)

We have tab-indented files for tests. But when you have space-indented document - this happens. It might have more than one space at the beginning.

I will look into this.

**Comment by KillyMXI** [comment]
Finally, an update. Major refactoring was unavoidable, but now it all should work fine.

**Comment by KillyMXI** [comment]
New version is now live in npm.

**Comment by kagfrog** [comment]
Thank you for all your work! I look forward to giving the new version a spin.

**Comment by 185driver** [comment]
Thank you for all your work! I look forward to giving the new version a spin.
