### ISSUE TITLE
Some visible whitespaces in browser are trimmed in the result

### ISSUE THREAD

**Issue by dzcpy** [html-to-text/node-html-to-text#206]
```javascript
htmlToText.fromString('<br>　　123<br>'
```
The line above should return the result like '\n　　123\n' instead of '\n123\n' since '　' is a visible white space in browser.
I would suggest that it's better to provide an option to choose what characters should not be trimmed.

**Comment by KillyMXI** [comment]
Thanks for pointing this out.

Your example uses Ideographic Space (`&#x3000;`). It is indeed preserved in browser.

I don't see a need for an option though. Since the goal of html-to-text is to approximate the browser behavior - we just have to make it behave with each whitespace character like a browser does.

I have to take a closer look into HTML spec, add extra tests, and work from there.

**Comment by KillyMXI** [comment]
I started to look into this issue and realized it will indeed require an option, with the default set true to HTML spec.
Have to meet conflicting demands.

**Comment by dzcpy** [comment]
Thanks for your reply. Also, browser's behaviours are a bit tricky too. For example,
`　　abc` is not trimmed by the browser, but
`　　<span>abc</span>` is trimmed. There is a lot of quirks.

**Comment by dzcpy** [comment]
Thanks very much for your reply.
Also, I found there are a lot of quirks too in the browser. For example:
`<p>　　abc</p>` is not trimmed, but
`　　<p>abc</p>` is trimmed. It's a bit wierd.

**Comment by KillyMXI** [comment]
Vivaldi (as well as any Chromium-based browsers, I suspect) shows the second example with Ideographic Spaces put on extra line.  
This aligns well with what I know at this point: text node containing these two characters is rendered in a block context and gets it's own line. It is not removed as HTML whitespaces, just not visible. It can be revealed with mouse selection.

I think this will be handled well once I'm done with the refactoring.

**Comment by KillyMXI** [comment]
I've pushed the update that should cover this, among many other things.

**Comment by KillyMXI** [comment]
New version is now live in npm.
