### ISSUE TITLE
docs: show code examples for deprecated options

### ISSUE THREAD

**Issue by dargmuesli** [html-to-text/node-html-to-text#211]
It would be much easier and quicker to implement if the deprecated options table in the readme contained code examples. For example the former `ignoreImage` option could now have `{ tags: { img: { format: 'skip' } } }` as an migration example. Just a nice to have :)
Congratulations on releasing v6! 🥳

**Comment by KillyMXI** [comment]
Hmm, good point. I will change plain text to code examples.

**Comment by KillyMXI** [comment]
Done in the repo.
Will get to the npm page with next version update (once there are some shippable fixes/features.)

Hopefully this reduces the cognitive load when getting familiar with the changes.
