### ISSUE TITLE
Breaks and block-level elements produce new lines even when preserveNewlines: false

### ISSUE THREAD

**Issue by gligoran** [html-to-text/node-html-to-text#212]
I would expect no new lines if I use `preserveNewlines: false`, but elements like `<br>` and `<p>` still produce them.

Example:

```js
const { htmlToText } = require("html-to-text");

const opts = {
    wordwrap: false,
    ignoreHref: true,
    ignoreImage: true,
    preserveNewlines: false,
};

const text = `<p>a</p>
<p>b</p><br/>c`;

console.log(htmlToText(text, opts));
// prints out: "a\n\nb\n\n\nc"
console.log(htmlToText(htmlToText(text, opts)));
// prints out: "a b c"
```

I would expect to get `"a b c"` by calling `htmlToText` just once.

**Comment by KillyMXI** [comment]
`preserveNewlines: false` just carries `\n` characters from input to output. It has nothing to do with block-level elements.

If you want to treat block-level elements as inline elements - set `format` to `inline` for these tags.

If you want to ignore `<br/>` tags - you can set `format` to `skip`, but that will not produce a space in their place. This can be solved with a custom formatter. (I think I will include it in the package later, as it can be handy in different situations.)

Following options will produce `a b c` on your example:

```javascript
  const opts = {
    formatters: {
      'placeholder': function (elem, walk, builder, formatOptions) {
        builder.addInline(formatOptions.text);
      }
    },
    tags: {
      'br': { format: 'placeholder', options: { text: ' ' } },
      'p': { format: 'inline' }
    }
  };
```

**Comment by KillyMXI** [comment]
No more questions, no necessary actions to take. I consider this resolved.
