### ISSUE TITLE
Missing div formatter

### ISSUE THREAD

**Issue by mannol** [html-to-text/node-html-to-text#213]
**Minimal HTML example**

```html
<div> Some text here </div>
<p> Paragraph text here </p>
```

**Options**

```javascript
{
    ignoreImage: true,
    tables: true,
    hideLinkHrefIfSameAsText: true,
    format: {
        div: 'skip',
    },
}
```

**Observed output**

```
Some text here
Paragraph text here
```

**Expected output**

```
Paragraph text here
```

**Version information**

- html-to-text: 6.0.0
- node: 10.16.3

----

There's no option to ignore div's or to handle them in any other way than default. This feature probably exists but it's not evident from documentation. I also tried using ```js tags: { div: { formatter: 'skip' } }``` but it doesn't help.

Thanks!

**Comment by KillyMXI** [comment]
The following is how it works:
```js
{
  tags: { 'div': { format: 'skip' } }
}
```

I see some inconsistency in the documentation with respect to these two words. I'll try to clear that up.

**Comment by mannol** [comment]
Oh awesome! Thank you very much, that works!

**Comment by KillyMXI** [comment]
Did some adjustments to Readme.
Hopefully it will be harder to misinterpret it now.
Updated Readme will get to npmjs page once there is anything else to ship.
