### ISSUE TITLE
Update suggestion for documentation

### ISSUE THREAD

**Issue by VBobCat** [html-to-text/node-html-to-text#216]
I just wanted to suggest that documentation be updated to show how to import it in an Angular2+ component:

```
import {htmlToText} from 'html-to-text/lib/html-to-text';
```

**Comment by KillyMXI** [comment]
I'm not familiar with Angular.

Do you really have to specify the path inside the package? Why?

Or is it only about import vs require syntax?

**Comment by VBobCat** [comment]
I had to write a custom control that allows plain text or html text edition, using CKEditor4. And htmlToText was very useful for me to implement the possibility that the user changes from one mode to another without losing its content, for it is converted on the fly. It took me some time to find the correct way of importing it, though. I just thought that would save this time to others after myself. Thank you very much for your attention!

**Comment by KillyMXI** [comment]
Your reply was not helpful unfortunately.

For now `html-to-text` only made with Node.js in mind.
If you're trying to use it in browser - you are on your own.

I plan to improve browser support in future updates.
Before that, I'd be happy to include some instructions, but only if they are provided by someone who actually understand what they are doing.

"I don't know why but this is what works for me" is not good enough, sorry.

**Comment by VBobCat** [comment]
Don't worry, it was only a suggestion, I'm not complaining nor urging you to do anything. By now I can only thank you guys because this package solved my problem beautifully.
Let me only explain I was not so clueless, I just had to browse the files in order to find which one hosted the main function, that is, `html-to-text/lib/html-to-text.js`.
