### ISSUE TITLE
Mutate text and skip elements conditionally

### ISSUE THREAD

**Issue by phrilrm** [html-to-text/node-html-to-text#217]
Hi, thanks for a great tool! I have some questions though which I am struggling with.

1. How can I mutate a text element, e.g, remove all newline \n and tab \t spaces etc
2. How can I conditionally skip an element? Currently I do this by setting the element to null in my formatting function.
  ```
 htmlToText(input, {
    formatters: {
      'doTheThings': function (elem, walk, builder, formatOptions) {
        const result =  myFunc(elem.children);
        if (!result) {
          elem = null;
          return;
        } else {
        ... continue
```
This is very hackish, so I'd love to know how to do this properly.

**Comment by KillyMXI** [comment]
This is very unclear question. And there are several aspects with the lack of understanding.

> 1. How can I mutate a text element, e.g, remove all newline \n and tab \t spaces etc

I can't see your end goal to suggest a course of actions. I won't get into deeper details before clarification, to avoid giving a misleading advice.

> 2. How can I conditionally skip an element? Currently I do this by setting the element to null in my formatting function.

Refer to the `skip` formatter ([source](https://github.com/html-to-text/node-html-to-text/blob/master/lib/formatter.js#L14)) - it skips an element unconditionally by not adding anything to the `builder` and not calling the `walk` callback - just does nothing and that's it. You can just return based on your predicate result.

**Comment by phrilrm** [comment]
Thanks for replying. I can see how it is unclear so I'll try to expand.

Basically what I am doing is parsing a complex CSV file of data which was exported from a legacy application. Some of the columns contain HTML which needs to be parsed to plain text. This is where this tool is used.
Some of the content of the HTML either needs to edited or ignored.
For example, some of the html might look like this:
```
<div>\n\tSome text content\n</div>
```
I would like this to be parsed to:
```
<div>Some text content</div>
```
With regards to skipping elements, here is an example:
```
<div>
  <div>This content needs to be kept</div>
  <div>\n&nbsp</div> <!-- Artifact from the legacy app. I need to ignore all these divs -->
  <div>This content needs to be kept</div>
</div>
```
So I would need to test that the text element here equals `\n&nbsp` and ignore that div. 

Does this make more sense? Feel free to ask for more clarifications.

I have lots of these files coming my way, so I'm trying to automate as much as possible.

**Comment by KillyMXI** [comment]
Yeah, it's much clearer now.
But I'm not sure `html-to-text` is the right tool for this. It's main goal is to produce human-readable plain text. (It's like a plain-text renderer, not a DOM manipulation tool.)

From your description it seems like you need to sanitize some html, without converting it to plain text. `html-to-text` is just not made for that. Some hacks are possible but for a very limited use (for systems that can render limited markup such as bold, italic, etc).

It's most likely better to look for something like [PostHTML](https://github.com/posthtml/posthtml) or a separate html parser that might come with a stringifier. For example, [htmlparser2](https://github.com/fb55/htmlparser2) used by `html-to-text` should be combinable with [dom-serializer](https://github.com/cheeriojs/dom-serializer) and you modify the DOM in-between.

**Comment by KillyMXI** [comment]
No actions to be taken. I consider this resolved.
