### ISSUE TITLE
image fomatters

### ISSUE THREAD

**Issue by wslee94** [html-to-text/node-html-to-text#219]
in version 4.X.X 
format : {
{
    image: (elm) => {
      if (elm.attribs.alt === 'Logo') {
        return '';
      }
      return `<img
        id='${elm.attribs.id || ''}'
        alt='${elm.attribs.alt || ''}'
        style='width:auto;height:auto;max-width:100%;bolder:0;'
        src='${elm.attribs.src || ''}'
      />
      `;
    },
  }
}

How does it work in version 6?

**Comment by KillyMXI** [comment]
1. formatters are now contained in the `formatters` key;
2. each formatter now have the signature `function (elem, walk, builder, formatOptions)` and returns nothing;
3. output is produced by calling the builder methods, [`addInline`](https://github.com/html-to-text/node-html-to-text/blob/master/lib/block-text-builder.js#L100) in particular;
4. `addInline` accepts optional second argument, when set to `true` it tells to avoid some text transformations, which is a good idea when outputting links or html *(once I will be able to get back to the code, I will release version 6.1.0 where builder methods will follow options object pattern and most positional args will be deprecated)*;
5. in case html formatting is especially important - it is possible to open a preformatted block and then add inline text...

**Comment by KillyMXI** [comment]
1. formatters are now contained in the `formatters` key;
2. each formatter now have the signature `function (elem, walk, builder, formatOptions)` and returns nothing;
3. output is produced by calling the builder methods, [`addInline`](https://github.com/html-to-text/node-html-to-text/blob/master/lib/block-text-builder.js#L100) in particular;
4. `addInline` accepts optional second argument, when set to `true` it tells to avoid some text transformations, which is a good idea when outputting links or html *(once I will be able to get back to the code, I will release version 6.1.0 where builder methods will follow options object pattern and most positional args will be deprecated)*;
5. in case html formatting is especially important - it is possible to open a preformatted block and then add inline text...

```js
formatters : {
    'image': (elm, walk, builder, formatOptions) => {
        if (elm.attribs.alt === 'Logo') {
            // do nothing
            return;
        }
        builder.addInline(
            `<img id='${elm.attribs.id || ''}' alt='${elm.attribs.alt || ''}' style='width:auto;height:auto;max-width:100%;bolder:0;' src='${elm.attribs.src || ''}' />`,
            true
        );
    },
}
```

**Comment by KillyMXI** [comment]
No follow-up comments. I consider this resolved.
