### ISSUE TITLE
Can't import the named export X from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by dargmuesli** [html-to-text/node-html-to-text#229]
Upgrading to v8 yields a build error for my project:

```
ERROR in ./node_modules/parseley/lib/parseley.mjs 171:30-37
Can't import the named export 'Grammar' from non EcmaScript module (only default export is available)
@ ./node_modules/selderee/lib/selderee.cjs
@ ./node_modules/@selderee/plugin-htmlparser2/lib/hp2-builder.mjs
@ ./node_modules/html-to-text/lib/html-to-text.js
@ ./node_modules/html-to-text/index.js
@ ./plugins/htmlToText.js
@ ./.nuxt/index.js
@ ./.nuxt/client.js
@ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
```
There are errors for Grammar, Parser, Picker, compareSpecificity, compile, isTag, normalize, parse1 and parse1: [source](https://github.com/maevsi/maevsi/pull/300/checks?check_run_id=2785421631)

How to go about this one?

**Comment by KillyMXI** [comment]
Hmm. It looks like something can't decide between cjs/mjs when used with Vue/nuxt.
I may have to tweak parseley/selderee packages.

I haven't started working on web compatibility yet (it was meant to be a node-only package) so I would be glad for an advice how to make dual packages work with more bundlers.

**Comment by KillyMXI** [comment]
`isTag` comes from htmlparser2 infrastructure. If that can't be sorted in node-html-to-text then it would require an upstream issue...

**Comment by KillyMXI** [comment]
On another look, I'm pretty confident about my packages.
There might be ways to dance around various bundler issues with obscure measures such as avoiding ".mjs" extension or using only default imports but I'm not going to support that and I think bundlers should be fixed instead.

The issue comes from Webpack.
Things to try:

- change Webpack version;
- add a rule for mjs into Webpack config (as in [there](https://stackoverflow.com/a/65982614/3423843) or [there](https://github.com/treshugart/react-shade/issues/8#issuecomment-488539553) or [there](https://github.com/formatjs/formatjs/issues/1395#issuecomment-518823361))

**Comment by MatthewAlbrecht** [comment]
Receiving a similar error, 

<img width="437" alt="Screen Shot 2021-06-09 at 12 48 34 PM" src="https://user-images.githubusercontent.com/7471272/121538313-8b695180-c9b9-11eb-9365-4eba03b9a879.png">

**Comment by KillyMXI** [comment]
@MatthewAlbrecht what framework/bundler you use? What version?
Can you try things from the previous comment?

**Comment by dargmuesli** [comment]
> add a rule for mjs into Webpack config (as in there or there or there)

All three solutions resolve the issue of build failure, but I'm pretty sure Nuxt has a reason to [exclude `node_modules` except for exceptions defined through `build.transpile`](https://github.com/nuxt/nuxt.js/blob/5934f41f0844dd9490b06ef9361a65c3052251de/packages/webpack/src/config/base.js#L334), but those exceptions don't work for me yet. I'll look into this further.

**Comment by dargmuesli** [comment]
Here we go: https://github.com/nuxt/nuxt.js/issues/6688

**Comment by dargmuesli** [comment]
The next version of Nuxt.js (after `2.15.6`) looks like it will include https://github.com/nuxt/nuxt.js/pull/9180. Having that and using
```
build: {
    transpile: [/\.mjs$/]
}
```
in `nuxt.config.js` resolves this issue for me.

**Comment by MatthewAlbrecht** [comment]
@KillyMXI We're using React/Webpack (create-react-app)

**Comment by claytonfbell** [comment]
Got this with a `create-react-app` project also.

```
Creating an optimized production build...
Failed to compile.

./node_modules/@selderee/plugin-htmlparser2/lib/hp2-builder.mjs
Can't import the named export 'Picker' from non EcmaScript module (only default export is available)
```

Version 7 works fine.

Using `"react-scripts": "^3.4.4",`

Webpack version from `package-lock.json` is 
```
    "webpack": {
      "version": "4.42.0",
```

**Comment by KillyMXI** [comment]
@claytonfbell in version 8 I started to use new packages. I follow generally recommended way to define dual packages there.
Webpack 4 falls in the crack between not knowing what mjs is and being able to handle it completely.
So, for as long as you stuck with Webpack version 4 - you have to tell it what to do via configuration. (see links in the [comment](https://github.com/html-to-text/node-html-to-text/issues/229#issuecomment-858535214) above).
Webpack 5 is apparently free of the issue.

**Comment by german-st** [comment]
> On another look, I'm pretty confident about my packages.
> There might be ways to dance around various bundler issues with obscure measures such as avoiding ".mjs" extension or using only default imports but I'm not going to support that and I think bundlers should be fixed instead.
> 
> The issue comes from Webpack.
> Things to try:
> 
> * change Webpack version;
> * add a rule for mjs into Webpack config (as in [there](https://stackoverflow.com/a/65982614/3423843) or [there](https://github.com/treshugart/react-shade/issues/8#issuecomment-488539553) or [there](https://github.com/formatjs/formatjs/issues/1395#issuecomment-518823361))
> 
> (Please report back if you find something that works for you. I'm pretty sure more people will run into this issue.)

@KillyMXI 

please see my comment:
[Error in CRA and html-to-text](https://github.com/html-to-text/node-html-to-text/issues/230#issuecomment-870570107)

**Comment by dargmuesli** [comment]
You might want to give Killy an hour or two to respond before creating another notification for all issue subscribers ;)

**Comment by german-st** [comment]
I'm not trying to rush someone) I'm making a link between issues that those who will search in the future can find the answer more conveniently and faster, if there is one)
