### ISSUE TITLE
preserveNewlines adds extraneous newlines when outside of some html elements

### ISSUE THREAD

**Issue by mdesson** [html-to-text/node-html-to-text#233]
**Minimal HTML example**

```html
<p>top</p>\n<p>bottom</p>
```

**Options**

```javascript
{ preserveNewlines: true }
```

**Observed output**

```
top




bottom
```

**Expected output**

```
top


bottom
```

**Version information**

- html-to-text: 8.0.0 (bug introduced in 6.0.0)
- node: v12.13.1

----

With `preserveNewlines` set to `true`, if `\n` is not placed inside a `<p>` tag, three extra newlines will be added. However if it's placed inside a `<p>` tag, it will have the desired output. 

Note that I haven't tested this with other html tags.

**Comment by KillyMXI** [comment]
Closed in favor of #232.
