### ISSUE TITLE
Node html-to-text adding extra newline where it shouldnt.

### ISSUE THREAD

**Issue by Midas-sudo** [html-to-text/node-html-to-text#235]
I'm trying to use html-to-text to parse some rss html, but the module seams to be adding new lines in the middle of frases. 

This is part of the html that im parsing. I was expecting some \n where the br tag is but he's placing newlines before that in between text
`Por forma a tentar aumentar a rapidez do processo de inscrição nos laboratórios na sexta-feira vamos separar as inscrições dos grupos de alunos com números ímpares (A) dos grupos de alunos com números pares (B).<br /><br /><div>Assim, os grupos de alunos...`
![image](https://user-images.githubusercontent.com/69457730/132073607-3cb234ca-29eb-4e2b-88e7-cae3bbeadf68.png)

Really dont know what could be the reason.
Thanks in advance.

**Comment by KillyMXI** [comment]
Html-to-text tried to fit output text into 80 characters width by default.

Set `wordwrap` option to `false` if you don't need that.

**Comment by Midas-sudo** [comment]
You'r right my bad should read the documentation more carefully. Working as desired with `wordwrap: false`. Thank you very much for the fast reply 👍  

![image](https://user-images.githubusercontent.com/69457730/132075175-63480679-dc2a-4dc2-9681-4e66d48d706e.png)
