### ISSUE TITLE
Support for encode

### ISSUE THREAD

**Issue by RizziSilva** [html-to-text/node-html-to-text#239]
Can the library handle encode from the text passed to it. Trying to remove tags from the text:

`
&lt;span style=&quot;color: rgb(29, 28, 29); font-family: Slack-Lato, appleLogo, sans-serif; font-size: 15px; font-variant-ligatures: common-ligatures; background-color: rgb(248, 248, 248);&quot;&gt;&amp;lt;span&amp;gt;&amp;lt;span style=&quot;font-size:9pt; font-family: Arial; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;&quot;&amp;gt;Random Text. &amp;lt;/span&amp;gt;&amp;lt; span style=&quot;font-size: 10.5pt; font-family: Comfortaa, cursive; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;&quot;&amp;gt;&amp;lt;/span&amp;gt;&amp;lt;span style=&quot;font-size: 9pt; font-family: Arial; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;&quot;&amp;gt; Random Text&amp;lt;/span&amp;gt;&lt;/span&gt;
`

Doesnt seen to work, but when using the normal text (without the encoded) it works as expected.

**Comment by KillyMXI** [comment]
`html-to-text` expects valid HTML input.
Escaped HTML is still valid HTML that is supposed to be rendered as text.

Consider `html-to-text` as a renderer, much like a browser.
If you store escaped HTML and want to render it in the browser - you unescape it beforehand. Do the same before rendering it with `html-to-text`.

Input preprocessing seems to me as an unnecessary responsibility for `html-to-text`.

**Comment by RizziSilva** [comment]
Do you have a opinion on how to normalize it before using the library? Right now in trying to remove the tags from a text in a backend using node and ts.

**Comment by KillyMXI** [comment]
[he](https://github.com/mathiasbynens/he) package should do the job, I think.

**Comment by RizziSilva** [comment]
The he library does solve this problem, thank you for the help.
