### ISSUE TITLE
Doesn't extract all text from a document

### ISSUE THREAD

**Issue by rick-rheo** [html-to-text/node-html-to-text#243]
**Minimal HTML example**

```html
curl the html from  https://www.afcsl.org/registration/
```

**Options**

```javascript
{}
```

**Observed output**

Most but not all of the text is returned.  Its missing the header  "2021 Fall Season Team Registration", and text below it.  The entire header (under the menu) is missing up to "After a team has been registered"

**Expected output**

```
All the text in the page
```

**Version information**

- html-to-text: 8.1.2
- node: 12.19.1

----

**Comment by rick-rheo** [comment]
Ugh. Sorry it was a server issue. Ignore me

**Comment by KillyMXI** [comment]
Version 8.1.2 doesn't exist though. I hope that was a typo.

**Comment by rick-rheo** [comment]
Not my finest hour writing that bug for sure   :(
