### ISSUE TITLE
Is disabling heading uppercase available from the command line?

### ISSUE THREAD

**Issue by natebrunette** [html-to-text/node-html-to-text#245]
**The goal**
I'm using this package to convert an Amazon SES variable template to plain text. If one of the variables is in a heading, it breaks because it can no longer map it correctly. I'm running this in a script that uses the aws cli to create the template and push it to aws.

**Best attempt**
I've tried running `npx html-to-text` with the `--uppercase=false` flag.

**The question**
How to prevent heading from getting converted to uppercase

**Prior research**
Read through the documentation, looked at the source. I couldn't figure out how input args were supposed to get mapped to the default options.

**Comment by KillyMXI** [comment]
Thank you for opening the issue. This way I can see some people actually use the CLI feature :)

CLI in it's current state is out of sync with the main code.
But the `minimist` package (middleware for CLI) has a useful but poorly documented (undocumented, basically) feature - dot chaining of argument names.
In combination with now deprecated `tags` option it allows to achieve the goal here.

Command line may look like this:

```
cat test.html | html-to-text --tags.h1.options.uppercase=0 --tags.h2.options.uppercase=0 > test.txt
```

Related issue: #185

New CLI package is almost done and I will publish it along with `html-to-text` version 9.
There is still some serious work left in different area before it's done though.

**Comment by natebrunette** [comment]
@KillyMXI thanks for the response. Is the flag potentially something different? I tried `--tags.h2.options.uppercase=0` and `--tags.h2.options.uppercase=false` and it's returning both in uppercase still.

**Comment by KillyMXI** [comment]
Oh. Sorry about that. Looks like I made it impossible to do a truthy comparison as early as in version 6.
Without that there is no way to supply true/false value to minimist without modifying the CLI code.

Fortunately, there is another workaround for headings, since they are almost the same as bare blocks:
```
html-to-text --tags.h2.format=block
```

**Comment by natebrunette** [comment]
Great, that's working, thanks!

**Comment by KillyMXI** [comment]
Hey, if you're still using html-to-text CLI, I've just published the new version:

<https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-text-cli>

Deprecated `tags` option is still available in this version:

```shell
cat test.html | html-to-text --!tags.h1.options.uppercase --!tags.h2.options.uppercase > test.txt
```

With new `selectors` array it looks like this:

```shell
cat test.html | html-to-text --selectors[] {} :selector=h1 :!options.uppercase {} :selector=h2 :!options.uppercase > test.txt
```

I actually didn't test it in Linux environment. If you try it - let me know if there are any issues.
