### ISSUE TITLE
fromString deprecated issue

### ISSUE THREAD

**Issue by moezbenrebah** [html-to-text/node-html-to-text#248]
I trying to configure emailing feature in my application and for that, I need to use templates for each email purpose, so htmlToText is needed, and when I used with .fromString it is marked as a deprecated signal from my eslint:
```javascript
// 2) Define email options
    const mailConfigs = {
      from: this.from,
      to: this.to,
      subject,
      html,
      text: htmlToText.fromString(html) // here html is a my HTML file path
    };
```

My question is: what is the alternative to "htmlToText.fromString" in order to get the same result?
Thank you

**Comment by KillyMXI** [comment]
```js
const { htmlToText } = require('html-to-text');
let text = htmlToText(html)

// or

const htmlToText = require('html-to-text');
let text = htmlToText.convert(html)
```
