### ISSUE TITLE
Vulnerability in minimist <= 1.2.5

### ISSUE THREAD

**Issue by bjkemp** [html-to-text/node-html-to-text#250]
minimist  <=1.2.5
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h

Upgrading to minimist 1.2.6 fixes the issue

**Comment by bjkemp** [comment]
Good luck with your situation and I hope everything gets better for you soon. Thank you for providing this package to the community.

**Comment by batflarrow** [comment]
Hey @KillyMXI any updates on this?

**Comment by KillyMXI** [comment]
I just published the version 8.1.1.

I'm going to fix another bug and publish 8.2.0 today.
