### ISSUE TITLE
TypeError: selderee.DecisionTree is not a constructor.

### ISSUE THREAD

**Issue by trevlar** [html-to-text/node-html-to-text#252]
**Minimal HTML example**

```html
<div>Hello</div><p>World</p>
```

**Options**

```javascript
convert("<div>Hello</div><p>World</p>");
```

**Observed output**

```
html-to-text.js:158 Uncaught TypeError: selderee.DecisionTree is not a constructor
    at compile (html-to-text.js:158:1)
    at convert (html-to-text.js:229:1)
```

**Expected output**

```
Hello\nWorld
```

**Version information**

- html-to-text: 
- node: 

----

I attempted to use 8.x, and 7.x with the same result.

**Comment by KillyMXI** [comment]
Are you using it in a web project?
What kind and version of building/packaging tool is used?

**Comment by trevlar** [comment]
> Are you using it in a web project? What kind and version of building/packaging tool is used?

I'm using it in a web project using create-react-app and TypeScript.

**Comment by KillyMXI** [comment]
This is likely to be related to #230
`create-react-app` relies on `webpack` and it is known to cause issues.

**Comment by KillyMXI** [comment]
Version 9 may also fix this issue when it's done, just because upstream packages will be more similar, less confusing for packaging tools.

**Comment by selva-tuva** [comment]
is there any quick fix for this?

**Comment by KillyMXI** [comment]
See the #230 thread. Webpack 4 needs some configuration.

**Comment by neirongkuifa** [comment]
Most likely it's due to missing cjs loader. If you're using ejected cra, it's pretty straightforward. Just add a new rule to process cjs files. Here's an example if you're using cra5:
```
 {
      test: /\.(cjs)$/,
      exclude: /@babel(?:\/|\\{1,2})runtime/,
      loader: require.resolve('babel-loader'),
      options: {
        babelrc: false,
        configFile: false,
        compact: false,
        presets: [
          [require.resolve('babel-preset-react-app/dependencies'), { helpers: true }],
        ],
        cacheDirectory: true,
        cacheCompression: false,
        sourceMaps: shouldUseSourceMap,
        inputSourceMap: shouldUseSourceMap,
      },
},
```

If your cra is not ejected, you can try package like craco to customized cra webpack config. The idea is the same. Add a rule so that webpack recognize cjs modules.

Ideally this should be handled from html-to-text package side.

**Comment by KillyMXI** [comment]
@neirongkuifa thank you.

What do you suggest to do inside html-to-text package?
The package knows nothing about webpack and react.
I don't know about these much either to fully understand your comment.
If really prefer to avoid adding any dependency with "react" in the name.

(With the next major version and bumped dependencies there is going to be more consistency in the upstream packages. But looking at this error with the immediate dependency - I'm not sure webpack 4 will be able to figure it out better after the update, as long as html-to-text itself is an old-style package.)

**Comment by neirongkuifa** [comment]
@KillyMXI This seems to be a promising solution. https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html.

**Comment by neirongkuifa** [comment]
I believe even you're not the maintainer of selderee, you can still use some packing tool to compile html-to-text to js bundle and use the above solution in html-to-text package.

**Comment by KillyMXI** [comment]
I am the maintainer of selderee. But I would like to avoid maintaining a bundle for frontenders either way.

When making selderee and other packages I was considering what file extensions to use. I can't remember the exact reasoning why I settled on the current way. All options seem to have their pros and cons and something downstream can break either way.

When I'll switch html-to-text package to TypeScript, dual mode will be a natural outcome. But the package is not quite ready yet for the transition I think. And I don't want to involve tsc before I'm comfortable to go all the way.

Perhaps I can try to configure rollup (which I'm using already) to produce both CommonJS and Module outputs for html-to-text. I made an attempt last year but it didn't work out for some reason so I stashed it. I'll try again.

**Comment by KillyMXI** [comment]
I published v9 preview version: `npm i html-to-text@preview`

I'd like to know whether the webpack compatibility issue still persists there.

**Comment by rmoghaddas-sedna** [comment]
I tested the preview version and seems it's been fixed.

**Comment by KillyMXI** [comment]
I don't know yet.
2022 sucks. I'm in another country, barely able to pay the rent, and can't make a buffer to free up a couple of weeks for an important feature.
Looks like I will have to change my plans and leave some parts for later just to release something in a reasonable time, but there are still things to do either way.
I will be able to look at it again at the end of this month, I think.

**Comment by rmoghaddas-sedna** [comment]
Do you think we could have a temp fix for this issue meanwhile? Any config we could add in cra-override to add the rule that can fix it.

**Comment by KillyMXI** [comment]
The issue:
- webpack 4 is a bit dumb and certain reach projects seem to be stuck with that version;
- html-to-text is a cjs package that depends on some mixed-mode packages.

Possible solutions:
- read #230, there is a [comment](https://github.com/html-to-text/node-html-to-text/issues/230#issuecomment-1120191301) that sounds close to what you're asking for;
- or use `html-to-text@preview` if nothing else works.

**Comment by rmoghaddas-sedna** [comment]
Didn't work for me. I pushed the new rule into rules in cra-override config file. But still seeing the exception raising in my page. I already upgraded to 8.2.* to have some fixes regarding that. Can't downgrade it to 7.*.
Even end of this month would work for me if we could have the release by that time.
I appreciate your time dude!
Let me know if I can help on anything!

**Comment by neirongkuifa** [comment]
@rmoghaddas-sedna Have you updated your start script? It won't work if you don't update the start script in package json. The issue is due to missing cjs file loader in cra5. Adding the loader should fix the issue, unless your override is not applied.

**Comment by goamn** [comment]
I tried to upgrade to get this bugfix for this issue: https://github.com/html-to-text/node-html-to-text/issues/232
However I got the error mentioned in this issue. A simple hack for anyone else in my place:
```
  //Known issue with html-to-text package: preserveNewlines flag results in doubling of new lines.
  //Can't upgrade to latest version as it is crashing (known issue: https://github.com/html-to-text/node-html-to-text/issues/252).
  //Below hack will be used instead.

  htmlToTextResult = htmlToTextResult.replaceAll('\n\n', '\n');
```

**Comment by goamn** [comment]
@KillyMXI I believe it was the latest version 8.2.1. I did not try v9 preview

**Comment by KillyMXI** [comment]
Version 9 is now public.
Based on little feedback I've got here, I assume webpack issue should be fixed now.
Please open a new issue in case there is any problem with version 9.
