### ISSUE TITLE
 Could not find a declaration file for module 'html-to-text'

### ISSUE THREAD

**Issue by qertis** [html-to-text/node-html-to-text#257]
Hello, I use TypeScript and show this error message:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/3893228/187027647-c54ed684-35d9-4699-b991-a2e722773320.png">

Install this types doesn't help IDEA
```bash
 npm i --save-dev @types/html-to-text
```

**Comment by KillyMXI** [comment]
I can't really comment on issues with IDEA (I don't use it outside of Java projects).

`@types/html-to-text` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-to-text/) exists, generally works and in sync with the code. I'm not among it's maintainers though.

- try to restart IDEA;
- try to clean the lock file and `node_modules` and reinstall packages;
- make sure package versions are up to date;
- try different versions to find possible breaking changes (don't use `^` or `~` during experiments);
- make sure there are no conflicts with global packages;
- make sure `@types/` packages work for you at all in IDEA...

That's all that comes to mind.
