### ISSUE TITLE
Support GitHub task lists

### ISSUE THREAD

**Issue by rscharfe** [html-to-text/node-html-to-text#260]
Would it be possible to support task lists better? I.e. this markdown list:

- [x] done item
- [ ] item still to do

... is represented in HTML roughly like this:

`<ul>`
`<li><input type="checkbox" checked="" /> done item</li>`
`<li><input type="checkbox" /> item still to do</li>`
`</ul>`

... and html-to-text currently turns it into:

` * done item`
` * item still to do`

Could it perhaps retain the distinction between checked and unchecked items, e.g. turn it into this instead?

` [x] done item`
` [ ] item still to do`

I noticed that when https://github.com/gitgitgadget/gitgitgadget used html-to-text to turn https://github.com/git/git/pull/1359 into https://github.com/gitgitgadget/git/releases/tag/pr-git-1359%2FAlphadelta14%2Farchive-recurse-submodules-v2, which was then sent to a text-only mailing list. The homogenized to-do list in the latter confused me for a while.

I realize that this is quite a narrow use case and there are probably different ways to represent to-do lists in HTML. Still: What do you think?

**Comment by KillyMXI** [comment]
html-to-text currently has no formatter for `input` tags. You can define your own.

Support for different input types can, perhaps, be added gradually, but I think when I decide to go for it - I'd better to add as many as possible to achieve a good forms support.
But that will have to wait.

You don't have to wait for it - just define your own custom formatter for `input[type=checkbox]` selector.

**Comment by rscharfe** [comment]
Good point. This:

`const { convert } = require('html-to-text');`
`const html = '<ul><li><input type="checkbox" checked=""> done item</li><li><input type="checkbox"> item still to do</li></ul>';`
`const text = convert(html, {`
`  formatters: {`
`    'checkedBox': function (elem, walk, builder, formatOptions) {`
`      builder.addInline('[x]');`
`    },`
`    'uncheckedBox': function (elem, walk, builder, formatOptions) {`
`      builder.addInline('[ ]');`
`    }`
`  },`
`  selectors: [`
`    { selector: 'input[type=checkbox][checked]', format: 'checkedBox' },`
`    { selector: 'input[type=checkbox]', format: 'uncheckedBox' }`
`  ]`
`});`
`console.log(text);`

... prints:

` * [x] done item`
` * [ ] item still to do`

The extra asterisks are a bit noisy, but bearable. Thank you for the quick and helpful reply!
