### ISSUE TITLE
v9: BlockTextBuilder.closeTable expects tableToString to be defined

### ISSUE THREAD

**Issue by webstech** [html-to-text/node-html-to-text#264]
Inside a formatter, `builder.closeTable({ colSpacing: 4 });` gets  `tableToString is not a function` error.

tableToString used to be used directly from `table-printer.js`.

Should `closeTable` use the old function if `tableToString` is undefined in the options?  The doc is not clear on what is required and there is no means for external formatters to provide tableToString from `table-printer.js`.

This was found in the typescript typings test driver so there may not be any real users affected.

**Comment by KillyMXI** [comment]
Oh. Took me a while but I see an issue now.

`builder.closeTable` got `tableToString` parameter in process of splitting the package, because builder is in the base package and tableToString is implementation specific.
This was done when I was rushing to implement html to markdown converter for the client (before they dropped this plan) and later I forgot to properly document it and also think how it is going to be used.
Naturally, now it would make sense to export `tableToString` from `html-to-text` for reuse. I'll think how to do it.

**Comment by KillyMXI** [comment]
The way I defined the type for `tableToString` currently:
https://github.com/html-to-text/node-html-to-text/blob/8a2dde66fe411a9a988cc5c424efc64af0b52b98/packages/base/src/typedefs.js#L269-L279
That should be enough to type the builder.

I think I will not expose `tableToString` function. The usage of `tableToString` function is the implementation detail of a particular formatter and I don't want the situation when I need to change the signature, but more people might depend on previous implementation already.
And there is definitely a room for rework for table formatting.

**Comment by KillyMXI** [comment]
To answer the question:

> Should closeTable use the old function if tableToString is undefined in the options? The doc is not clear on what is required and there is no means for external formatters to provide tableToString from table-printer.js.

- `tableToString` parameter is required (yes, breaking change). In my jsdoc comments this is expressed by the absence of square brackets;
- type definition is now disconnected from what is found in `table-printer.js` - refer to jsdoc comments.

Yes, not very friendly. But so is the problem of table formatting.

**Comment by KillyMXI** [comment]
`TablePrinterCell[][]` is what is built by table related functions.

https://github.com/html-to-text/node-html-to-text/blob/8a2dde66fe411a9a988cc5c424efc64af0b52b98/packages/base/src/typedefs.js#L260-L267

`TablePrinter` is any function from `TablePrinterCell[][]` to `string`.

There are two questions:

- Testing. If you can mock a `TablePrinter` function, then it should be enough for tests (If it doesn't matter what it does - then it should be easy);
- Usage. I have two not fun implementations. I have a couple more implementations in mind with different levels of "not fun"-ness. I'm still not confident in whether I have the right API surface and whether shared implementations might be useful without modifications.

So far, the easiest way around working with formatters is to copy-paste an existing one and customize.
I will get to the point eventually where this part will be far more refined. I don't feel like I should invite more people to get comfortable with the current implementation.

Ok, I still haven't made a final decision.
Maybe I can expose it like `implementation.defaultTablePrinter` or something like that.
It will still be a subject for breaking changes.

**Comment by webstech** [comment]
> Ok, I still haven't made a final decision.

No problem.  You could defer until a user opens an issue.  The test driver is ready pending the other issue.

**Comment by KillyMXI** [comment]
Updated `closeTable` options type to be consistent.

I also briefly considered injecting the default `TablePrinter` implementation through `BlockTextBuilder` constructor, but it seems rather limited and unfair solution just to pretend having some default implementation. So I discarded the idea for now.

**Comment by webstech** [comment]
Thanks for your quick response to this and clarifying the documentation.    Sorry that I had missed some of the subtleties of the internal doc.
