### ISSUE TITLE
Could encodeCharacters support emojis?

### ISSUE THREAD

**Issue by webstech** [html-to-text/node-html-to-text#267]
I thought it might be handy to use the `encodeCharacters` option to change emojis into short codes.

Tried the following:
```
    encodeCharacters: {
            "😀": ":smiley:"
    },
```
The output was `:smiley:�`.
Tried changing the code to use `codePointAt` with no success. I may have done it wrong but the regex looked somewhat reasonable.

Can emojis be supported for this?  They are larger numbers (ie >4 hex digits).

Full disclosure:
I have no actual requirement for this and just thought I would try it in the test code.  I am raising the question so anyone else with the same idea will find the answer.

**Comment by KillyMXI** [comment]
The purpose of this feature - safely escape characters that might have special meaning in output text.
More specifically, I needed a way to prevent markdown from breaking by a rogue unescaped `_` or `|` for example. Perfect solution would've only escaped characters in contexts where they are ambiguous, but I don't know how to achieve that yet.

The reason it doesn't work with smileys:
Regex only takes a single character from a key.
Smileys are not single characters, and some of them not even a single code point.
It would actually require a significant effort to properly isolate any of them. ([Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) only comes with Node 16 and it would mean I have to segment each text fragment just to check whether there is any symbol to replace.)

How replacer is constructed:
https://github.com/html-to-text/node-html-to-text/blob/2b18dacdaa5a356afe24487e4ba12556be1376f3/packages/base/src/index.js#L164-L185
The reason to encode characters is to produce a guaranteed valid regex without worrying about specific escape rules.
I can potentially encode whole keys - that should make it work with smileys.
There is one caveat though - it won't be obvious to the programmer, but the order of keys becomes important: if there is any key that is a substring of another key (or can partially overlap another key) - it should not appear first. That includes basic and compound emojis.
Perhaps, I can sort the entries array by the key length (descending) to avoid some of this risk. But the risk of partial overlap remains, even if less likely in practice.
That would also make the name `encodeCharacters` inaccurate to what it does.

**Comment by KillyMXI** [comment]
Now I figured that, while taking one character is sufficient for my purpose, with a bit more effort I can get and encode the first code point.
That should make it work for any weird characters, which is good.
Coincidentally, it will make it work for some emojis. But not for compound ones.

**Comment by KillyMXI** [comment]
I published 9.0.2 with the change.
Now it takes the first code point.

While at it, I also allowed values in the dictionary to be `string | false` - this is mainly for html to md package that will come with some defaults, to make a cleaner way to disable them.

**Comment by webstech** [comment]
Thank  you very much.  It is working.  I appreciate the quick response.
