### ISSUE TITLE
Got <style>

### ISSUE THREAD

**Issue by yuribrown** [html-to-text/node-html-to-text#275]
version> 9.0.3

options>
    const text = convert(res.data, {
            wordwrap: 130,
    });

html fragment> as attached: "html_page.zip"
[html_page.zip](https://github.com/html-to-text/node-html-to-text/files/10394531/html_page.zip)

output I got> as attached: "result_i_got.txt"
[result_i_got.txt](https://github.com/html-to-text/node-html-to-text/files/10394542/result_i_got.txt)

expected output> only text content, no style content

**Comment by KillyMXI** [comment]
Interesting.
Look at the line 1056 of `html_page.html`. It contains this `<style>` html in escaped form:

```html
</script><textarea id="s_is_result_css" style="display:none;">
&lt;style data-for=&quot;result&quot; type=&quot;text/css&quot; &gt;body{color:#333;background:#fff;padding:6px 0 0;margin:0;position:relative}body,th,td,.p1,.p2{font-family:arial}...
```

`html-to-text` just sees it as plain text and unescapes it.

You can hide it with a rule like `{ selector: 'textarea[style="display:none;"]', format: 'skip' }`
