### ISSUE TITLE
How to avoid getting href content of link in html page?

### ISSUE THREAD

**Issue by yuribrown** [html-to-text/node-html-to-text#277]
How to avoid getting href content of link in html page?

**Comment by KillyMXI** [comment]
`selectors: [ { selector: 'a', options: { ignoreHref: true } } ]`
This will ignore href content of all links.
You can add more specific selectors if you want to hide href only for some links.
There is also `hideLinkHrefIfSameAsText` option in case you just want to hide repeating links.

**Comment by yuribrown** [comment]
Got it. Thank you! It works.
