### ISSUE TITLE
Parsing email content generates excess line breaks

### ISSUE THREAD

**Issue by arggh** [html-to-text/node-html-to-text#279]
**The goal**

I'm trying to parse a plain text version of the HTML part of an email.

**Best attempt**

This parses the emails, but with almost all email clients it seems to double all line breaks.

```js
return convert(html, {
    wordwrap: false,
    limits: {
      maxBaseElements: 10,
      maxChildNodes: 200,
      maxDepth: 2000,
    },
    selectors: [
      { selector: 'blockquote', format: 'skip' },
      { selector: 'img', format: 'skip' },
      {
        selector: 'a',
        options: {
          linkBrackets: false,
          ignoreHref: true,
        },
      },

      {
        selector: 'p',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
      {
        selector: 'pre',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
      {
        selector: 'div',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
      {
        selector: 'br',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
    ],
  });
```

**The question**
Is there a sane set of settings that handles emails nicely? My initial reaction was trying to set `leadingLineBreaks` or `trailingLineBreaks` to 0 for `div`s or `br`s, but the formatter only accept 1 or larger.

Problem seems to be, that most email software wrap `<br>` into a `<div>`, like so:

```html
<div class="">Hello,</div>
<div class=""><br class="" /></div>
<div class="">my name is John Doe.</div>
<div class=""><br class="" /></div>
<div class=""><br class="" /></div>
<div class="">
  Best regards, John<br class="" />
  <div>
```

or

```html
<p>Please note the explicit line break at the end of a paragraph<br /></p>
```

...which in an email client looks like this:

```
Hello,

my name is John Doe.

Best regards, John
```

but with `html-to-text`, it becomes:

```
Hello,


my name is John Doe.



Best regards, John
```

**Prior research**
I've tried (and somewhat succeeded) by running a regular expression - replace -function on the end result.

I also managed to get rid of the line breaks using `format: 'inline'` for divs, but this again gets rid of the line breaks a little too much.

While I continue my trial & error efforts, I was wondering, if people more familiar with transforming html, and html emails to be specific, into text, have a battle-tested strategy to handle this use case?

I'm very new to this library, so I apologise beforehand if I've missed something obvious in the docs.

**Comment by KillyMXI** [comment]
Hmm

Browser output:

```
Hello,

my name is John Doe.


Best regards, John
```

This should be the reference for me. Email client collapsing two empty lines into one is not like a browser behavior and no spec would be able explain it.

So, the issue is that in this example `html-to-text` doesn't behave like a browser. It is not immediately obvious to me how to fix it though. I'll have to research this topic further some other time.


> Is there a sane set of settings that handles emails nicely? My initial reaction was trying to set `leadingLineBreaks` or `trailingLineBreaks` to 0 for divs or brs, but the formatter only accept 1 or larger.

`br`s are not block-level elements, so these options won't affect them.
`0` value for `div`s should ideally make it identical to `format: inline`, except it can break some line length math and thus not allowed.


Workaround:

From this example it looks like `<br>`s are simply not needed. So, `{ selector: 'br', format: 'skip' }`
This produces the result as in browser.

I'm not sure how to collapse `<div class=""><br class="" /></div><div class=""><br class="" /></div>` to a single empty line, other than in pre- or post-processing.

**Comment by arggh** [comment]
I'm trying to collect a large sample set of email client html output and I'm starting to realize that this is probably an impossible task (without tailoring the solution on a per-client basis).

Emails have markup like this:

```html
<div
  dir="auto"
  style="
    overflow-wrap: break-word;
    -webkit-nbsp-mode: space;
    line-break: after-white-space;
  "
>
  <div>
    Best regards,<br /><br />John Doe<br /><br />Doing What Johns Do<br />Check
    me out on Youtube
  </div>
</div>
```

...which breaks the `{ selector: 'br', format: 'skip' }` approach.

Then lots of email clients also output these:

```html
<div><br/></div>
```

...which is an easy target for a regular expression to swap those for a single `<br/>`, but then Google for example does this:

```html
<div dir="ltr">
  I forgot to mention I hate emails, and it's a miracle people still use this 60's tech. Talk about network effects!
  <div><br /></div>
  <div>Maybe we will use emails forever.</div>
  <div><br /></div>
  <div>Br, arggh</div>
</div>
```

...where removing the `<div><br /></div>` breaks the flow, since the preceding part wasn't wrapped in a an element and the line break actually served a purpose.

If anything was to be improved in `html-to-text` for this use case, I suppose it's selectors. For example, `div br:only-child` or `div br:last-child` could be useful.

Or a carefully crafted _magical_ preset that handles 95% of the cases.

**Comment by arggh** [comment]
Using a few regular expressions as a preprocessor, I was able to accomplish a pretty decent solution. I'll probably improve on it as time passes and new emails enter the test matrix, but pretty much the flow is:

1. regexp replacing
- replace weird html markup by [enter email provider] with sane markup
- replace weird html markup by [enter another email provider] with sane markup
- replace weird html markup by [enter yet another email provider] with sane markup
- ...

2. run `html-to-text` with a bunch of email provider specific selectors and some basic config:

```js
{
  wordwrap: false,
  limits: {
    maxBaseElements: 10,
    maxChildNodes: 200,
    maxDepth: 2000,
  },
  selectors: [
      { selector: 'script', format: 'skip' },
      { selector: 'style', format: 'skip' },
      { selector: 'blockquote', format: 'skip' },
      { selector: 'img', format: 'skip' },
      { selector: '.gmail_attr', format: 'skip' },
      { selector: '.Zm-_Id_-Sgn1', format: 'skip' },
      { selector: 'hr', format: 'skip' },
      {
        selector: 'a',
        options: {
          linkBrackets: false,
          ignoreHref: true,
        },
      },
      {
        selector: 'p',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
      {
        selector: 'pre',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
      {
        selector: 'div',
        options: { leadingLineBreaks: 1, trailingLineBreaks: 1 },
      },
  ]
}
```

Thank you for your help & for maintaining this package, it was very useful.

**Comment by KillyMXI** [comment]
No problem.

Hopefully I'll be able to deliver my solution for dealing with bad markup in a foreseeable future. My html to markdown package release is also blocked by similar issue - it is just more critical for a strict output markup.
