### ISSUE TITLE
Entity after script tag results in HTML being copied.

### ISSUE THREAD

**Issue by galenhuntington** [html-to-text/node-html-to-text#285]
**Minimal HTML example**

```html
<style>a{}</style>&apos;<br/>
```

**Observed output**

```
'<br/>
```

**Expected output**

```
'

```

**Version information**

- html-to-text: 9.0.4
- node: 18.14.2

----

The problem seems to arise with either a `<script>` or `<style>` block, followed by text with an entity (`&blah;`).  HTML afterwards gets copied over literally without any further text conversion.

**Comment by KillyMXI** [comment]
Thank you for the report.

It's a `htmlparser2` issue. I opened the issue upstream: https://github.com/fb55/htmlparser2/issues/1426

For now, it should be possible to set `decodeEntities` to false and deal with entities afterwards.

`html-to-text` before version 9.0.0 should also be unaffected.

**Comment by KillyMXI** [comment]
Upstream issue is fixed in `htmlparser2` 8.0.2.
And I published `html-to-text` 9.0.5 with updated dependencies.
