### ISSUE TITLE
Extracted output is not clean it contain escape characters like /n/n or so on

### ISSUE THREAD

**Issue by coolb0y** [html-to-text/node-html-to-text#289]
**The goal**
I am scraping  html pages to extract clean text from them so I can put them into millisearch for searching purpose

**Best attempt**

After using this configuration in code 
```
const options = {
    ignoreHref: true, // ignore <a> tags and their content
    ignoreImage: true, // ignore <img> tags and their content
    noLinkBrackets: true, // do not add square brackets around links
    preserveNewlines: false, // preserve newlines in the text
    noLinkBrackets: true,
    ignoreHref: true,
    wordwrap: 1,
    ignoreImage: true,
    encodeCharacters:{"\n":" ",
    "\r":" ",
    "\t":" ",
    "\f":" ",
    "\v":" ",
    "\u00A0":" ",
    "*":" "},
    whitespaceCharacters: '\t\r\n',
    selectors: [
        { selector: 'a', format: 'skip'},
        { selector: 'img', format: 'skip'},
        { selector: 'script', format: 'skip'},
        { selector: 'style', format: 'skip'},
        { selector: 'br', options:{itemPrefix: " "} },
        {selector:'header',format:'skip'},
        {selector:'footer',format:'skip'},
        { selector: 'ul', options: { itemPrefix: " " }},
        { selector: 'ol', options: { itemPrefix: " " }},
       // { selector: 'li', options: { itemPrefix: " " }},
        { selector: 'p', options: { itemPrefix: " " }},
        { selector: 'h1', options: { itemPrefix: " " }},
        { selector: 'h2', options: { itemPrefix: " " }},
        { selector: 'h3', options: { itemPrefix: " " }},
        { selector: 'h4', options: { itemPrefix: " " }},
        { selector: 'h5', options: { itemPrefix: " " }},
        { selector: 'h6', options: { itemPrefix: " " }},
        { selector: 'table', options: { itemPrefix: " " }},
       // { selector: 'tr', options: { itemPrefix: "" }},
        //{ selector: 'td', options: { itemPrefix: "" }},
        //{ selector: 'th', options: { itemPrefix: "" }},
        //{ selector: 'title', options: { itemPrefix: "" }},
      ],
      decodeEntities: true,
  };
  
```

I got this as output check next para .  You can see here it contains escape characters like \n\n and sometimes / in between 
`
 BOOKSTORE\n\n \n\n  \n\n\n\n\n\n\n\n-\n\n\n\nUNESCO / Published 1974\nRuth M. Stone / Published 1976\nAlan P. Merriam / Published 1981\nAlan P., Merriam / Published 1970\nDouglas Harold. Varley / Published 1970\nJohn Collins\nPublished 1981\nChris Stapleton, Chris May / Published 1990\nFredrick Kaufman, John P. Guckin / Published 1979\nDavid Fanshawe\nDavid Fanshawe\nGraeme Ewens, et al / Paperback / Published 1992\nCecelia Conway / Paperback / Published 1995\nFrancis Bebey / Paperback / Published 1990\n \nJohn Chernoff / Paperback / Published 1981\nJerry Silverman, Kenneth B. Clark / Library Binding / Published 1993\nJerry Silverman / Paperback / Published 1994\nVeit Erlmann / Paperback / Published 1991\nVeit Erlmann / Hardcover / Published 1992\nSean Barlow, et al / Hardcover / Published 1995\nVarious / Audio CD / Published 1995\nAldon Lynn Nielsen / Paperback / Published 1997\nTricia Rose / Paperback / Published 1994\nImamu Amiri Baraka, et al / Paperback / Published 1983\nGary Stewart / Paperback / Published 1992\n\n\n\nPeter Sarpong\nKatherine Mallows\nP. J. Nhlapho\nNicholas N
`
**The question**
I am trying to figure out to change this configuration such that it contains only clean text. No escape character or backward or forward slash or any other special character.

**Prior research**
I have tried all the possible combination but cannot be helped . The title and tr th fields of html cannot be customized so If any one can help me that would be great. Thanks in Advance.

**Comment by KillyMXI** [comment]
What is the input HTML for this output?

**Comment by coolb0y** [comment]
[](https://github.com/coolb0y/ngo-file/blob/main/bookstore.html )  this is the file Which I am trying to scrap right now.

**Comment by KillyMXI** [comment]
1. you should probably start with empty options. The options you provided contain a lot of nonsense. Not all those options do what you hope they do;
2. not everything you might want to do is the responsibility of `html-to-text`.

That being said, there is still a lot that can be achieved before you have to resort to text post-processing.

```js
  {
    wordwrap: false,
    encodeCharacters: { '/': '' }, // this wasn't the purpose of this option, but if it works - it works. You might have to use post-processing instead if you want to avoid double spaces as well.
    selectors: [
      { selector: 'img', format: 'skip' },
      { selector: 'hr', format: 'skip' },
      { selector: 'br', format: 'skip' },
      { selector: 'form', format: 'skip' },
      { selector: 'a', options: { ignoreHref: true } }, // link text can be a part of content, you might only need to avoid href when indexing
      { selector: 'a[href="#TOP"]', format: 'skip' }, // not something you'd search for
      { selector: 'p', format: 'inline' }, // since you don't care about block formatting for search indexing, you can mark everything inline
      { selector: 'table', format: 'inline' },
      { selector: 'h1', format: 'inline' },
    ]
  }
```

You are also incorrect about `\n`. `html-to-text` simply outputs line breaks. What you show is the output escaped after `html-to-text` to be a valid js string.

If there is anything more you'd like to do with the text - you don't have to do it all in one step with `html-to-text`, you can do it afterwards, post-processing the text with regular expressions.
Instead of `encodeCharacters: { '/': '' }`, I would rather do `text.replace(/\s+\/\s+/g, ' ')`.
If you want to guarantee the output to be a string with no line breaks - that's also best achieved with a regex replace. `encodeCharacters` does not affect characters that are inserted as a part of layout.
