### ISSUE TITLE
Using in a React Native app

### ISSUE THREAD

**Issue by tom-dudman** [html-to-text/node-html-to-text#291]
**The goal**
Use `html-to-text` in a React Native app

**Best attempt**
I've installed the package, and imported the `convert` function in the relevant component.

```
import { convert } from "html-to-text";

...

const body = convert(htmlBody);
```

**The question**
`run-android` and `run-ios` output the following warning:

```
Package html-to-text has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /<project path>/node_modules/html-to-text/package.json
```

And the app crashes with the following message:

```
error: Error: While trying to resolve module `html-to-text` from file `/<project path>/src/components/email.js`, the package `/<project path>/node_modules/html-to-text/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/<project path>/node_modules/html-to-text/lib/html-to-text.cjs`. Indeed, none of these files exist:

  * /<project path>/node_modules/html-to-text/lib/html-to-text.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /<project path>/node_modules/html-to-text/lib/html-to-text.cjs/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

**Prior research**
Tried exporting `./package.json` from `package.json`.  Tried node versions from `14.18.1` up to `18.16.0`.

**Comment by KillyMXI** [comment]
Man. There is one thing I hate more than webpack. It is the whole React infrastructure. They ruin JavaScript for everyone else.

> `Package html-to-text has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /<project path>/node_modules/html-to-text/package.json`

What?

> `* /<project path>/node_modules/html-to-text/lib/html-to-text.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`

It doesn't recognize `cjs` as a valid extension and doesn't check "extensionless" file either.
Especially confusing since from the previous warning we can conclude it knows about exports so it can't be that old.
If there is a way to configure it to recognize additional file extension - that should solve this.
Alternatively, you can try `html-to-text` 8.2.1 - before it switched to dual mode.

Overall, this seems to be an issue of React Native specifically or React pipeline as a whole.
I'm not qualified to help with it.
If you can debug the issue and explain what is missing - I can include the changes unless they cause inconveniences elsewhere.

**Comment by KillyMXI** [comment]
Relevant issues:
https://github.com/thysultan/stylis/issues/233
https://github.com/emotion-js/emotion/issues/1986
https://www.reddit.com/r/expo/comments/w14tjo/unable_to_resolve_module_cjs/

Looks like there is a way to provide additional file extensions.

**Comment by KillyMXI** [comment]
Ah right, I forgot the bundler will have to deal with all my upstream packages as well.

If you can't update the bundler itself, another way might be, perhaps, to bundle problematic dependency first and use that.
Not sure if something like <https://esm.sh/> con do that for you.

**Comment by tom-dudman** [comment]
Success!  The steps to solve for me were:

- Use version `8.2.1`
- Add a `resolver.sourceExts` to `metro.config.js` which included `cjs` and `mjs` in the list of extensions

Thank you very much for your help with this.  Its saved me lots of work maintaining two strings in parallel.

**Comment by KillyMXI** [comment]
I'm curious whether version 9 works with `resolver.sourceExts` or what kind of error you get otherwise (and what version of metro you're working with).

**Comment by tom-dudman** [comment]
With `9.0.5` when running `npx react-native start`, `npx react-native run-android` or `npx react-native run-ios` I get the warning:

```
Package html-to-text has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /<project path>/node_modules/html-to-text/package.json
```

The project uses react-native `0.62.2` ... is that the metro version?... I'm not sure.

**Comment by KillyMXI** [comment]
So it runs, just has this warning?

I found this issue: https://github.com/uuidjs/uuid/issues/444
and this comment: https://github.com/ai/nanoevents/issues/44#issuecomment-602010343
Looks like I can add `"./package.json": "./package.json"` to my exports whenever I will be releasing the next version, but it shouldn't affect the functionality in any way other than this warning, so no need to hurry.

If metro is in the dependency tree, then it should be possible to find it in `node_modules` or in `package-lock.json`.
