### ISSUE TITLE
Get data in blocks

### ISSUE THREAD

**Issue by cosbgn** [html-to-text/node-html-to-text#293]
**Problem to solve**
Preserves "some" of the structure from the original HTML 

**What works**
Instead of returning a string it returns an array of blocks (e.g. table, div, section, nav, etc)

**What is missing**
I can't get only a specific part of text

**How the missing feature should be implemented**
Ideally a new option like `convert(html, { blocks: true })`

**Bigger picture**
First of all thank you for this library, works great and it's simple to use. My issue is that I would like to have some structure. For example from this html:

```
<body>
	<nav>
		<ul>
			<li>navlink</li>
		</ul>
	</nav>
	<p> some content </p>
	<table>...</table>
</body>
```
I would like to get something like this: 

```
[

	{type:'nav', content:"navlink"},
	{type:'p', content:"some content"},
	{type:'table', content:"..."}

]
```
I'm now wondering if perhaps it's out of scope and I should somehow add a dom parser before `node-html-to-text`, this is impossible right now, right?

**Comment by KillyMXI** [comment]
This sounds like some specific use case which might not be useful for everyone and for which I still have no clear understanding. People might have different ideas how to split a document in blocks.

Currently there is `baseElements` set of options.
You can specify `baseElements.selectors` array for all things you consider blocks (in your definition) and want to process.
All results will be merged into single output string though. I might think about a way to output results for each base element separately, but I need a real-world example where it might be useful.

There are multiple hacky solutions that might be done currently to separate outputs for base elements. But running a separate parser to get your block first would be more clean and robust solution for now.

**Comment by cosbgn** [comment]
Yes, an example of a use case would be to extract a table from a website, as I don't know the site beforehand, it would be useful for me to know which part of the text is the actual table, but I do agree that this might actually be better to do using a html parser and then pass the output to node-html-to-text. Thanks for confirming it!

**Comment by cosbgn** [comment]
Yes, to be honest this library is so great at doing what it does that I wouldn't want it to actually solve this problem. It's perfect as it is, you give html as input and it gives text as output. 

From the HTML you should anyways be able to know if it's a table or now, so no need to pollute this great library with a function very few people will need.
