### ISSUE TITLE
converting html fails

### ISSUE THREAD

**Issue by stvischer** [html-to-text/node-html-to-text#294]
I tried to compile the markup in the attached file.

[htmlToText.txt](https://github.com/html-to-text/node-html-to-text/files/11684885/htmlToText.txt)

Problematic are the lines 768 - 771 and 784 -787

I logged out the [...this.lines, this.nextLineWords] array in InlineTextBuilder's toString method in line 310:

- [ [], undefined, [ 'Spende', '€', '1.000.-' ] ]
- [ [], undefined, [ 'Gesamtsumme', '€', '1.000.-' ] ]

It leads to an error in line 311 when it calls undefined.join()

**Comment by KillyMXI** [comment]
It would've been more appropriate to use the bug report template when opening the issue.
At the very minimum, I need to know `html-to-text` version you're using and exact options you provide to `compile` or `convert` function.

It seems this issue is related to #282 - fixed in version 9.0.4.

**Comment by KillyMXI** [comment]
No follow up - I consider this solved.
