### ISSUE TITLE
h1 and P are conflicting

### ISSUE THREAD

**Issue by chantorak** [html-to-text/node-html-to-text#298]
**Minimal HTML example**

```html
-
```

**Options**

```javascript
const { convert } = require('html-to-text');

const text = convert(content, {
    baseElements: {
        selectors: ["p", "h1"]
    }
});
console.log(text);
```

**Observed output**

```
HEALTH.
WELLNESS.
HAPPINESS.
```

**Expected output**

The expected output to include P and h1 contents

**Version information**

- html-to-text: 9.0.5
- node: 16

----

If remove the h1, the output will included the P content, somehow the h1 is conflicting with the P

**Comment by KillyMXI** [comment]
That's not minimal HTML example.

```js
const html = `
<h1>heading</h1>
<p>paragraph</p>
<h1>heading</h1>
<p>paragraph</p>
<h1>heading</h1>
<p>paragraph</p>`;

const options = { baseElements: { selectors: ['p', 'h1'] } };

const text = htmlToText(html, options);
console.log(text);
```

Output:
```
paragraph

paragraph

paragraph


HEADING  


HEADING


HEADING

```

Front page of `https://nutritionhappiness.com/` contains one `<h1>` heading with the content you've provided and one `<p>` paragraph which is empty.

```html
<h1 class="t677__title t-title t-title_xs " field="title" style="font-size:66px;"><div style="line-height:68px;" data-customstyle="yes"><i>Health.<br>Wellness.<br>Happiness.<strong></strong></i></div></h1>
```

```html
<p class="gm-style-mot"></p>
```

Not sure what content you observe when you remove `h1` and only keep `p` from selectors. If no base elements are found, default value for `baseElements.returnDomByDefault` is `true` and that will result in entire page being processed. But with one empty paragraph that should result in empty output.
You are probably doing something wrong and I can't tell you what exactly.
