### ISSUE TITLE
how to convert url to markdown ?

### ISSUE THREAD

**Issue by firefoxOnFire** [html-to-text/node-html-to-text#300]
**The goal**
*What are you trying to achieve?*

**Best attempt**
*What you've tried to do so far to achieve your goal?*

**The question**
*What you can't figure out yourself?*

How to get `[google](http://google.com)` from `<a href="http://www.google.com">google</a>`  instead `google [http://google.com]`
I am converting html to markdown. But I can't figure it out how to achieve this.

**Prior research**
*Where did you look and what you've tried to do so far in order to figure out the answer before writing here? Is there anything else you can try?*

**Comment by KillyMXI** [comment]
You would need a custom formatter.
Refer to readme: [/packages/html-to-text/README.md#override-formatting](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-text/README.md#override-formatting)
You can reuse the one from WIP html to markdown converter: [/packages/html-to-md/src/md-formatters.js#L134](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-md/src/md-formatters.js#L134)

I suspect many users of `html-to-text` need markdown instead. Unfortunately, I have other difficulties that currently prevent me from finishing that one.

**Comment by firefoxOnFire** [comment]
> You would need a custom formatter. Refer to readme: [/packages/html-to-text/README.md#override-formatting](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-text/README.md#override-formatting) You can reuse the one from WIP html to markdown converter: [/packages/html-to-md/src/md-formatters.js#L134](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-md/src/md-formatters.js#L134)
> 
> I suspect many users of `html-to-text` need markdown instead. Unfortunately, I have other difficulties that currently prevent me from finishing that one.

Thanks for the reply sir. I somehow managed to get the format after modifying this [This ](https://github.com/html-to-text/node-html-to-text/blob/5b7ca1c1a736a730c9a4fa1b6db6172e50f4ee3e/packages/html-to-text/src/text-formatters.js#L149)

But it would be great to add this functionality. Thanks.

**Comment by firefoxOnFire** [comment]
> You can reuse the one from WIP html to markdown converter: [/packages/html-to-md/src/md-formatters.js#L134](https://github.com/html-to-text/node-html-to-text/blob/master/packages/html-to-md/src/md-formatters.js#L134)

I am very much new to js. And I don't know how to call this I can't find this in documentation. Please can you take an example. If you get time. Thanks.

**Comment by KillyMXI** [comment]
> But it would be great to add this functionality. Thanks.

It will be in a separate html to markdown package WHEN I'm able to get back to it and finish it.

> And I don't know how to call this I can't find this in documentation. Please can you take an example.

You have everything you need.
Refer to readme for how to define custom formatters, built-in formatter methods work the same way so can be used as inspiration for your custom formatters.

**Comment by firefoxOnFire** [comment]
> It will be in a separate html to markdown package WHEN I'm able to get back to it and finish it.

Got it. Thanks. 

> You have everything you need.

Yeah, sorry.
