### ISSUE TITLE
tableToString(rows, formatOptions.rowSpacing ?? 0, formatOptions.colSpacing ?? 3), Unexpected token '?'

### ISSUE THREAD

**Issue by ktjbrowne** [html-to-text/node-html-to-text#301]
Hello, I'm receiving the following error.

html-to-text/lib/html-to-text.cjs:1878
    tableToString: (rows) => tableToString(rows, formatOptions.rowSpacing ?? 0, formatOptions.colSpacing ?? 3),
                                                                           ^
SyntaxError: Unexpected token '?'

Is there any work around?
Using the following code with Langchain.js also.

`const { compile } =  require('html-to-text');
const { RecursiveUrlLoader } = require('langchain/document_loaders/web/recursive_url');

const url = "https://www.yorkshirewater.com";

const compiledConvert = compile({ 
  wordwrap: 130,
  selectors: [
    { selector: 'table', format: 'skip' }
  ]
}); // returns (text: string) => string;

const loader = new RecursiveUrlLoader(url, {
  extractor: compiledConvert,
  maxDepth: 0
});

const docs = await loader.load();`

Thank you for any help.
K.

**Comment by KillyMXI** [comment]
What environment you're using?
`html-to-text` version 9 is targeting Node >=14.

For other envoronments such as browsers - refer to compatibility table at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing for this particular line.
I can't guarantee there aren't more incompatibilities.

If you can't update the environment - you'd have to stick to `html-to-text` version 8 or transpile it to ECMAScript version below 2020 as a part of your building pipeline.

**Comment by ktjbrowne** [comment]
Thank you. 
node v12
I have reverted to v8.
many thanks!
