### ISSUE TITLE
ul tag without text wrap

### ISSUE THREAD

**Issue by Adilmrqureshi** [html-to-text/node-html-to-text#303]
**The goal** 
I'm trying to display an unordered list in a PDF. I parse the string, which comes from the database and use PDF kit to generate a PDF from the parsed string.

**Best attempt**
`const convert = compile({
  wordWrap: null,
  selectors: [
    { selector: "ul", options: { itemPrefix: "• " } },
    { selector: "ul.li", options: { wordWrap: false } },
  ],
});
`

**The question**
Why does the text wrap, and how can I make `<li>` tags take the full width of the screen.

**Comment by KillyMXI** [comment]
`wordwrap` should be in all lowercase. Names are case-sensitive.

Interesting catch. Most properties are in camelCase. Seems like `wordWrap` might be more fitting. I'll think whether I should support that.
Other somewhat questionable words present in settings: `newlines`, `whitespace`, `uppercase`. I'm more solid those don't require the change.

Side note:
Your options are not correct in some other way as well, although that is not relevant to the issue:
- selector `ul.li` means `<ul class="li">`;
- this selector has no format provided;
- `li` elements won't be selected as long as the default formatter is used for `ul` - it will process them internally.

**Comment by Adilmrqureshi** [comment]
Thank you
