### ISSUE TITLE
How do you decode & convert in one pass?

### ISSUE THREAD

**Issue by nrathi** [html-to-text/node-html-to-text#307]
**The goal**
I want to extract the text from a string that looks like this: `"&lt;p&gt;&lt;b&gt;This hardcover book titled &amp;quot;Phantom Prey&amp;quot; by John Sandford was published in 2008 by Penguin Publishing Group. It is a thrilling work of fiction that falls under the categories of &amp;quot;Thrillers/General,&amp;quot; &amp;quot;Thrillers/Suspense,&amp;quot; and &amp;quot;Mystery &amp;amp; Detective/General.&amp;quot; The book measures 9.3in x 6.3in x 1.2in and has 384 pages. It is written in English and weighs 20 oz.&lt;/b&gt;&lt;/p&gt;&lt;br /&gt;&lt;p&gt;&lt;b&gt;The story is about a detective named Lucas Davenport who solves a series of murders in Minneapolis. The book is in excellent condition and ready to be enjoyed by someone who loves a good thriller. Get your hands on this exciting read and enjoy the rollercoaster ride of suspense and mystery.&lt;/b&gt;&lt;/p&gt;"`

**Best attempt**
`const res = convert(convert(str), { wordwrap: false });`
This seems to work, but it seems wrong.

**The question**
Is there a way to do what I want, without calling the function twice?

**Comment by KillyMXI** [comment]
You have text with all HTML entities encoded/escaped.
You need to find any other way to decode HTML entities first to get the HTML.
There are many ways to do this task, I won't be choosing any specific one for you.

The fact that calling `convert` twice does work is a byproduct of it also decoding HTML entities by default.

**Comment by nrathi** [comment]
Okay thank you, I'll just call it twice then for simplicity.

**Comment by KillyMXI** [comment]
Yes, this might work fine, as long as you don't care about some performance overhead.
