### ISSUE TITLE
Convert is not a function error

### ISSUE THREAD

**Issue by raumildhandhukia** [html-to-text/node-html-to-text#316]
html-to-text is installed, alongside the types.
When I try to use convert function it throws an error that function does not exist.

body field will have entire HTML page (including headers, meta data etc)

```
import { analyze } from "../.../somefile.ts";
import { convert } from "html-to-text";

export async function POST(req: Request) {
  try {
    const reqBody = await req.json();
    const { body, labels } = reqBody;
    const emailTextFromHTML = convert(body);
    const text = await analyze(emailTextFromHTML, labels);
    return new Response(text, { status: 200 });
  } catch (e) {
    return new Response("Internal Server Error - While Analyzing Email", {
      status: 500,
    });
  }
}
```

Am I using it wrong? I tried using this function with options as well, it is not working in my Next.js 14 application.

**Comment by KillyMXI** [comment]
Most likely cause - you are not importing what you think you do.
First of all, check what version of `html-to-text` is *actually* imported.
`convert` was introduced in version 8.

This is related to #218 if not a duplicate.

**Comment by raumildhandhukia** [comment]
And you were absolutely correct. Its time I stop using npm install, instead add latest version in package.json.

Thank you!!! It worked.

**Comment by raumildhandhukia** [comment]
Not Issue, Version Issue
