### ISSUE TITLE
Erroneously removes >

### ISSUE THREAD

**Issue by remko** [html-to-text/node-html-to-text#37]
html-to-text removes >, even if the < is escaped.

```
$ echo "&lt;b>Hello" | ./bin/cli.js 
<b Hello
```

**Comment by mlegenhausen** [comment]
Why you do not escape both?

**Comment by dule** [comment]
But that's assuming the source text has escaped it. If we don't control where the input comes from, a string like `<p> Good > Bad </p>` will become `Good Bad`.

**Comment by dule** [comment]
Though I suppose this is actually a problem with https://github.com/tautologistics/node-htmlparser/issues/72

**Comment by KillyMXI** [comment]
`html-to-text` uses [htmlparser2](https://github.com/fb55/htmlparser2) currently.

This issue seem to be outdated. I can't reproduce it.

GitBash under Windows:

```bash
$ echo "&lt;b>Hello" | node.exe ./bin/cli.js
<b>Hello
```

pwsh under Windows:

```powershell
PS> echo "&lt;b>Hello" | node ./bin/cli.js
<b>Hello
PS> echo "<p> Good > Bad </p>" | node ./bin/cli.js
Good > Bad
```
