### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by simison** [html-to-text/node-html-to-text#45]
Please, now it's really hard to realise what has changed between versions.

Thanks for the package btw! Using it at [Trustroots](https://www.trustroots.org/).

**Comment by mlegenhausen** [comment]
For the up coming releases I will add a change log. I can understand that it is hard to track down the changes.

**Comment by simison** [comment]
:+1:

**Comment by KillyMXI** [comment]
Outdated issue.
