### ISSUE TITLE
Add version tags

### ISSUE THREAD

**Issue by simison** [html-to-text/node-html-to-text#46]
They're simple yet effective. :-)

Here; https://github.com/werk85/node-html-to-text/releases

**Comment by mlegenhausen** [comment]
How can I access this page over the menu?

**Comment by simison** [comment]
Click "releases" from https://github.com/werk85/node-html-to-text

**Comment by simison** [comment]
Github also has a nice guide: https://help.github.com/articles/creating-releases/

**Comment by mlegenhausen** [comment]
Ah thanks found them ;) Thanks for the link.

**Comment by KillyMXI** [comment]
I think this can be safely closed.
