### ISSUE TITLE
First element of sublist not indented

### ISSUE THREAD

**Issue by dplassmann** [html-to-text/node-html-to-text#47]
Nested lists are not formatted correctly: the first element of the sublist appears on the same line as the parent list.  This snippet:

```
<ul>
  <li>1
    <ul>
      <li>2
        <ul>
          <li>3.1</li>
          <li>3.2</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

should output as:

```
* 1
  * 2
    * 3.1
    * 3.2
```

but instead outputs as

```
* 1 * 2 * 3.1
       * 3.2
```

**Comment by mlegenhausen** [comment]
Good catch. Pull requests are always welcome ;)

**Comment by jamiehill** [comment]
No one picked this up in 4 years? :(

**Comment by jamiehill** [comment]
Have had a look through the code and seems to be `htmlparser2` auto closing tags where `openImpliesClose`.  Not as simple a task to fix, as the dom object prodived to htmlToText already has the nested lists messed up.

Have you had any more thoughts on this @mlegenhausen ?  Would be happy to implement, if you could share your thoughts.

**Comment by mlegenhausen** [comment]
@jamiehill would be happy if you could take a look.

**Comment by jamiehill** [comment]
Submitted :)

**Comment by KillyMXI** [comment]
Outdated issue.
