### ISSUE TITLE
No newline after tables

### ISSUE THREAD

**Issue by volgunin** [html-to-text/node-html-to-text#52]
When a table is followed by either h1, h2, p, or div there is no newline between them.

For example:

``` html
<html>
<body>
    <table>
        <tr>
            <td>Issue Date:</td>
            <td>Wed, 01 Oct 2014</td>
        </tr>
    </table>
    <p>Passengers</p>
</body>
</html>
```

becomes:

``` text
Issue Date: Wed, 01 Oct 2014Passengers
```

instead of:

``` text
Issue Date: Wed, 01 Oct 2014
Passengers
```

I use this call:

``` javascript
var text = HtmlToText.fromString(html)
```

**Comment by volgunin** [comment]
I think I figured it out. Could be my fault. But the documentation is a bit misleading.

If I use:

```
var text = HtmlToText.fromString(html, {tables: true})
```

I get output right.

Docs say that tables parameter affects table selection, not table formatting. Default value ([]) selects all tables, but in plain text without ending newline. Maybe due to a missing break in walk function?

**Comment by mlegenhausen** [comment]
Maybe, would be nice if you could investigate in the problem.

**Comment by KillyMXI** [comment]
Version 6 comes with the support for block-level tags.
Paragraphs and tables separated from adjacent tags by 2 line breaks by default (adjustable):
```
Issue Date:   Wed, 01 Oct 2014

Passengers
```
