### ISSUE TITLE
Does not process tables with uppercase tags

### ISSUE THREAD

**Issue by volgunin** [html-to-text/node-html-to-text#53]
When a table has one of its tags in uppercase the output is incorrect.

For example:

``` html
<html>
<body>
    <table>
        <TR>
            <td>Issue Date:</td>
            <td>Wed, 01 Oct 2014</td>
        </TR>
    </table>
    <p>Passengers</p>
</body>
</html>
```

becomes:

``` text
Passengers
```

I use:

```
var text = HtmlToText.fromString(html, {tables: true})
```

**Comment by mlegenhausen** [comment]
Seems to be a smaller problem. A bugfix seems easy. Pull requests are welcome.

**Comment by volgunin** [comment]
There is a pull request for this issue and #54. The change is small.

Regards.

**Comment by KillyMXI** [comment]
Outdated issue.
#56 was merged ages ago.
