### ISSUE TITLE
Does not process tables with center tag

### ISSUE THREAD

**Issue by volgunin** [html-to-text/node-html-to-text#54]
Although center tag is deprecated in HTML5, some vendors still use it in their emails.

For example:

``` html
<html>
<body>
    <table>
    <center>
        <tbody>
            <tr>
                <td>Issue Date:</td>
                <td>Wed, 01 Oct 2014</td>
            </tr>
        </tbody>
    </center>
    </table>
</body>
</html>
```

becomes:

``` text
```

I use:

```
var text = HtmlToText.fromString(html, {tables: true})
```

**Comment by mlegenhausen** [comment]
Yes centering is not supported. Pull requests are welcome.

**Comment by volgunin** [comment]
When the parser encounters a center tag it stops traversing the tree and the table does not appear in output at all. So this issue is not about centering. 

I created a pull request for this issue and #53 as they are closely related.

Regards.

**Comment by mlegenhausen** [comment]
Oh sorry for late response, will take a look tomorrow.

**Comment by KillyMXI** [comment]
Outdated issue.
#56 was merged ages ago.
