### ISSUE TITLE
Disable "Transform headlines to uppercase text"

### ISSUE THREAD

**Issue by euglv** [html-to-text/node-html-to-text#58]
Is there option available to disable "Transform headlines to uppercase text" functionality?

**Comment by mlegenhausen** [comment]
Currently not, but I am open for new functionality. Maybe you can provide a pull request.

**Comment by pklada** [comment]
https://github.com/werk85/node-html-to-text/pull/86 <-- this would allow for non-uppercased headings

**Comment by KillyMXI** [comment]
Very outdated issue.
