### ISSUE TITLE
Question: does this work in the browser

### ISSUE THREAD

**Issue by garemoko** [html-to-text/node-html-to-text#67]
I appreciate this is a node library. Is there a version of this or anything similar that works in the browser?

**Comment by mlegenhausen** [comment]
There are already people who are using the library with browserify.

**Comment by malpiatko** [comment]
It would be great if you put that in the wiki. Would be easier for node beginners.

**Comment by mlegenhausen** [comment]
Normally the `node-` prefix of the project indicates that it should be used primarily in node environment.

**Comment by jimmywarting** [comment]
A browser version could be built smarter since it can "walk" the DOM (child) elements and wouldn't need [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) library to parse the content. Hence the `node-` prefix. 

This may work on the client side with browserify, but I would certainly not recommend. It probably would be better of to find a client side alternative to this. All the (sub) dependencies would make the end script file quite large...

**Comment by mlegenhausen** [comment]
Exchanging the html parser by a modern one which is usable in node and browser environments with a smaller overhead would be nice.

**Comment by giorgio79** [comment]
Found this solution https://github.com/dustinsoftware/html-to-plaintext

**Comment by fiatjaf** [comment]
In the browser you can use `.innerText` which does wonders.

**Comment by jimmywarting** [comment]
>In the browser you can use .innerText which does wonders.

@fiatjaf i wouldn't say `.innerText` dose wonders... you only get the text, it won't be transformed like this lib dose it. try getting the text from a table with `.innerText` and see what you get

**Comment by jkupczak** [comment]
Has any more talk been done about making this work in the browser? I assume not but I wanted to ask before I attempt to make my own solution. I searched around but couldn't find any other front-end equivalents to this package.

**Comment by michaelbukachi** [comment]
Found this package:
https://github.com/EDMdesigner/textversionjs

**Comment by KillyMXI** [comment]
Time to close this.
People were using this package in web projects for quite a while now.
Version 9 moves CLI to external package and hopefully solves some issue with webpack.
There should be no obstacles left from this being equally supported both in node and web environment.
