### ISSUE TITLE
Why use blankspace instead of \n

### ISSUE THREAD

**Issue by nswbmw** [html-to-text/node-html-to-text#71]
```
htmlToText.fromString('<div>one</div><div>two</div>')
```

will get `one two`, wht not `one\ntwo` ?

**Comment by mlegenhausen** [comment]
cause there is now line break `<br/>`? I can not determine by this code if you want a block or an inline layout.

**Comment by nswbmw** [comment]
I know `<br/>` will convert to `\n`. `<div>` is a block-level element, so `<div>one</div><div>two</div>` will print two lines like:

```
one
two
```

After `htmlToText.fromString`, it becomes `one two`, only print in one line.

**Comment by mlegenhausen** [comment]
Ok sounds reasonable. Pull request is welcome ;)

**Comment by jimmywarting** [comment]
Should actually be done for all Block elements...

article, aside, blockquote, body, br, button, canvas, caption, col, colgroup, dd, div, dl, dt, embed, fieldset, figcaption, figure, footer, form, h1–6, header, hgroup, hr, li, map, object, ol, output, p, pre, progress, section, table, tbody, textarea, tfoot, th, thead, tr, ul, video

**Comment by vzaidman** [comment]
any progress on that?

**Comment by scottfr** [comment]
Can @oldlam's pull request be merged in?

**Comment by cuixiping** [comment]
> Should actually be done for all Block elements...
> 
> article, aside, blockquote, body, br, button, canvas, caption, col, colgroup, dd, div, dl, dt, embed, fieldset, figcaption, figure, footer, form, h1–6, header, hgroup, hr, li, map, object, ol, output, p, pre, progress, section, table, tbody, textarea, tfoot, th, thead, tr, ul, video

@jimmywarting ,

I think that `button, canvas, embed, object, textarea, video` are not block elements.

**Comment by gillesKuhorn** [comment]
Is it merged ?
I have the same problem..

**Comment by KillyMXI** [comment]
Version 6 is now aware of block-level tags.
More common ones are included in the default configuration.
