### ISSUE TITLE
The example with tables is not formatted correctly

### ISSUE THREAD

**Issue by iunctim** [html-to-text/node-html-to-text#85]
The example test.html is not being formatted correctly. The table format ist not being preserved in the plain text.

**Comment by mlegenhausen** [comment]
Can you please specify what is not correctly formatted?

**Comment by yacon** [comment]
works properly for me. At the first try I forgot to set the "table" option.
Maybe thats the cased in this issue as well?

**Comment by KillyMXI** [comment]
I think this can be closed safely.

"table" option is often overlooked indeed.
