### ISSUE TITLE
selector for baseElement

### ISSUE THREAD

**Issue by cAstraea** [html-to-text/node-html-to-text#96]
Hello.
Any idea how would go about selecting all divs that have an id that start with pf ? like pf1 , pf2 , etc.
baseElement: ['div#pf \* ???']  is there a wildcard match for this ?

**Comment by mlegenhausen** [comment]
Wildcards are currently not supported via the `baseElement` option. If you want to contribute new features you are free to provide a pull request for this feature.

**Comment by KillyMXI** [comment]
Version 8 is now live.
It allows to use the new selectors feature for base elements as well.
It uses CSS selectors syntax though.
Attribute value selectors can be used for partial match:

```js
{
  baseElements: {
    selectors: [
      'div[id^="pf"]'
    ]
  }
}
```
